// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Two tools cover the entire API: <api>_search to discover endpoints, and
// <api>_execute to invoke one. This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search+execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the two agent-facing tools that
// cover the whole API surface. Called from RegisterTools in place of the
// per-endpoint registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("cloudbeds_search",
			mcplib.WithDescription("Search the cloudbeds API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("cloudbeds_execute",
			mcplib.WithDescription("Execute one cloudbeds API endpoint by its endpoint_id (from cloudbeds_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by cloudbeds_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// search+execute pair needs at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	keywords   []string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:         "access-token.create",
		Method:     "POST",
		Path:       "/access_token",
		Summary:    "Query the authorization server for an access token used to access property resources.</br> If the automatic delivery...",
		Positional: []string{},
		keywords:   codeOrchKeywords("access-token", "create", "Query the authorization server for an access token used to access property resources.</br> If the automatic delivery...", "/access_token"),
	},
	{
		ID:         "append-custom-item.create",
		Method:     "POST",
		Path:       "/appendCustomItem",
		Summary:    "Append single, or multiple, custom items and their associated payments to an existing one in a Reservation, House...",
		Positional: []string{},
		keywords:   codeOrchKeywords("append-custom-item", "create", "Append single, or multiple, custom items and their associated payments to an existing one in a Reservation, House...", "/appendCustomItem"),
	},
	{
		ID:         "create-allotment-block.create",
		Method:     "POST",
		Path:       "/createAllotmentBlock",
		Summary:    "Retreive allotment blocks @apiQuery {Integer} propertyID Property ID",
		Positional: []string{},
		keywords:   codeOrchKeywords("create-allotment-block", "create", "Retreive allotment blocks @apiQuery {Integer} propertyID Property ID", "/createAllotmentBlock"),
	},
	{
		ID:         "create-allotment-block-notes.create",
		Method:     "POST",
		Path:       "/createAllotmentBlockNotes",
		Summary:    "Add a note to an allotment block",
		Positional: []string{},
		keywords:   codeOrchKeywords("create-allotment-block-notes", "create", "Add a note to an allotment block", "/createAllotmentBlockNotes"),
	},
	{
		ID:         "delete-adjustment.delete",
		Method:     "DELETE",
		Path:       "/deleteAdjustment",
		Summary:    "Voids the AdjustmentID transaction on the specified reservationID",
		Positional: []string{},
		keywords:   codeOrchKeywords("delete-adjustment", "delete", "Voids the AdjustmentID transaction on the specified reservationID", "/deleteAdjustment"),
	},
	{
		ID:         "delete-allotment-block.create",
		Method:     "POST",
		Path:       "/deleteAllotmentBlock",
		Summary:    "Delete allotment blocks",
		Positional: []string{},
		keywords:   codeOrchKeywords("delete-allotment-block", "create", "Delete allotment blocks", "/deleteAllotmentBlock"),
	},
	{
		ID:         "delete-app-property-settings.create",
		Method:     "POST",
		Path:       "/deleteAppPropertySettings",
		Summary:    "Delete app property settings",
		Positional: []string{},
		keywords:   codeOrchKeywords("delete-app-property-settings", "create", "Delete app property settings", "/deleteAppPropertySettings"),
	},
	{
		ID:         "delete-guest-note.delete",
		Method:     "DELETE",
		Path:       "/deleteGuestNote",
		Summary:    "Archives an existing guest note.",
		Positional: []string{},
		keywords:   codeOrchKeywords("delete-guest-note", "delete", "Archives an existing guest note.", "/deleteGuestNote"),
	},
	{
		ID:         "delete-reservation-note.delete",
		Method:     "DELETE",
		Path:       "/deleteReservationNote",
		Summary:    "Archives an existing reservation note.",
		Positional: []string{},
		keywords:   codeOrchKeywords("delete-reservation-note", "delete", "Archives an existing reservation note.", "/deleteReservationNote"),
	},
	{
		ID:         "delete-room-block.delete",
		Method:     "DELETE",
		Path:       "/deleteRoomBlock",
		Summary:    "Deletes a room block",
		Positional: []string{},
		keywords:   codeOrchKeywords("delete-room-block", "delete", "Deletes a room block", "/deleteRoomBlock"),
	},
	{
		ID:         "delete-webhook.delete",
		Method:     "DELETE",
		Path:       "/deleteWebhook",
		Summary:    "Remove subscription for webhook. Read the [Webhooks guide](https://integrations.cloudbeds.com/hc/en-us/articles/36000...",
		Positional: []string{},
		keywords:   codeOrchKeywords("delete-webhook", "delete", "Remove subscription for webhook. Read the [Webhooks guide](https://integrations.cloudbeds.com/hc/en-us/articles/36000...", "/deleteWebhook"),
	},
	{
		ID:         "get-allotment-blocks.list",
		Method:     "GET",
		Path:       "/getAllotmentBlocks",
		Summary:    "Retrieve allotment blocks",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-allotment-blocks", "list", "Retrieve allotment blocks", "/getAllotmentBlocks"),
	},
	{
		ID:         "get-app-property-settings.list",
		Method:     "GET",
		Path:       "/getAppPropertySettings",
		Summary:    "Returns the app property settings",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-app-property-settings", "list", "Returns the app property settings", "/getAppPropertySettings"),
	},
	{
		ID:         "get-app-settings.list",
		Method:     "GET",
		Path:       "/getAppSettings",
		Summary:    "Get the current app settings for a property.<br />",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-app-settings", "list", "Get the current app settings for a property.<br />", "/getAppSettings"),
	},
	{
		ID:         "get-app-state.list",
		Method:     "GET",
		Path:       "/getAppState",
		Summary:    "Get the current app integration state for a property.<br /> This call is only available for third-party integration...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-app-state", "list", "Get the current app integration state for a property.<br /> This call is only available for third-party integration...", "/getAppState"),
	},
	{
		ID:         "get-available-room-types.list",
		Method:     "GET",
		Path:       "/getAvailableRoomTypes",
		Summary:    "Returns a list of room types with availability considering the informed parameters ### Group account support",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-available-room-types", "list", "Returns a list of room types with availability considering the informed parameters ### Group account support", "/getAvailableRoomTypes"),
	},
	{
		ID:         "get-currency-settings.list",
		Method:     "GET",
		Path:       "/getCurrencySettings",
		Summary:    "Get currency settings",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-currency-settings", "list", "Get currency settings", "/getCurrencySettings"),
	},
	{
		ID:         "get-custom-fields.list",
		Method:     "GET",
		Path:       "/getCustomFields",
		Summary:    "Gets custom fields list<br /> ¹ data.displayed = 'booking' - Display this field to guests on the booking engine.<br...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-custom-fields", "list", "Gets custom fields list<br /> ¹ data.displayed = 'booking' - Display this field to guests on the booking engine.<br...", "/getCustomFields"),
	},
	{
		ID:         "get-dashboard.list",
		Method:     "GET",
		Path:       "/getDashboard",
		Summary:    "Returns basic information about the current state of the hotel",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-dashboard", "list", "Returns basic information about the current state of the hotel", "/getDashboard"),
	},
	{
		ID:         "get-email-schedule.list",
		Method:     "GET",
		Path:       "/getEmailSchedule",
		Summary:    "Returns a list of all existing email scheduling. This call is only available for third-party integration partners,...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-email-schedule", "list", "Returns a list of all existing email scheduling. This call is only available for third-party integration partners,...", "/getEmailSchedule"),
	},
	{
		ID:         "get-email-templates.list",
		Method:     "GET",
		Path:       "/getEmailTemplates",
		Summary:    "Returns a list of all existing email templates. This call is only available for third-party integration partners,...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-email-templates", "list", "Returns a list of all existing email templates. This call is only available for third-party integration partners,...", "/getEmailTemplates"),
	},
	{
		ID:         "get-files.list",
		Method:     "GET",
		Path:       "/getFiles",
		Summary:    "Returns a list of files attached to a hotel or group profile, ordered by creation date",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-files", "list", "Returns a list of files attached to a hotel or group profile, ordered by creation date", "/getFiles"),
	},
	{
		ID:         "get-group-notes.list",
		Method:     "GET",
		Path:       "/getGroupNotes",
		Summary:    "Returns group notes",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-group-notes", "list", "Returns group notes", "/getGroupNotes"),
	},
	{
		ID:         "get-groups.list",
		Method:     "GET",
		Path:       "/getGroups",
		Summary:    "Returns the groups for a property",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-groups", "list", "Returns the groups for a property", "/getGroups"),
	},
	{
		ID:         "get-guest.list",
		Method:     "GET",
		Path:       "/getGuest",
		Summary:    "Returns information on a guest specified by the Reservation ID parameter",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-guest", "list", "Returns information on a guest specified by the Reservation ID parameter", "/getGuest"),
	},
	{
		ID:         "get-guest-list.list",
		Method:     "GET",
		Path:       "/getGuestList",
		Summary:    "Returns a list of guests, ordered by modification date ### Group account support",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-guest-list", "list", "Returns a list of guests, ordered by modification date ### Group account support", "/getGuestList"),
	},
	{
		ID:         "get-guest-notes.list",
		Method:     "GET",
		Path:       "/getGuestNotes",
		Summary:    "Retrieves a guest notes",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-guest-notes", "list", "Retrieves a guest notes", "/getGuestNotes"),
	},
	{
		ID:         "get-guests-by-filter.list",
		Method:     "GET",
		Path:       "/getGuestsByFilter",
		Summary:    "Returns a list of guests matching the selected parameters ### Group account support",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-guests-by-filter", "list", "Returns a list of guests matching the selected parameters ### Group account support", "/getGuestsByFilter"),
	},
	{
		ID:         "get-guests-by-status.list",
		Method:     "GET",
		Path:       "/getGuestsByStatus",
		Summary:    "Returns a list of guests in the current status (Not Checked In, In House, Checked Out or Cancelled), sorted by...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-guests-by-status", "list", "Returns a list of guests in the current status (Not Checked In, In House, Checked Out or Cancelled), sorted by...", "/getGuestsByStatus"),
	},
	{
		ID:         "get-guests-modified.list",
		Method:     "GET",
		Path:       "/getGuestsModified",
		Summary:    "Returns a list of guests based on their modification date. Note that when a guest checks in or checks out of a room,...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-guests-modified", "list", "Returns a list of guests based on their modification date. Note that when a guest checks in or checks out of a room,...", "/getGuestsModified"),
	},
	{
		ID:         "get-hotel-details.list",
		Method:     "GET",
		Path:       "/getHotelDetails",
		Summary:    "Returns the details of a specific hotel, identified by 'propertyID'",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-hotel-details", "list", "Returns the details of a specific hotel, identified by 'propertyID'", "/getHotelDetails"),
	},
	{
		ID:         "get-hotels.list",
		Method:     "GET",
		Path:       "/getHotels",
		Summary:    "Returns a list of hotels, filtered by the parameters passed ### Group account support",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-hotels", "list", "Returns a list of hotels, filtered by the parameters passed ### Group account support", "/getHotels"),
	},
	{
		ID:         "get-house-account-list.list",
		Method:     "GET",
		Path:       "/getHouseAccountList",
		Summary:    "Pulls list of active house accounts",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-house-account-list", "list", "Pulls list of active house accounts", "/getHouseAccountList"),
	},
	{
		ID:         "get-housekeepers.list",
		Method:     "GET",
		Path:       "/getHousekeepers",
		Summary:    "Returns a list of housekeepers ### Group account support",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-housekeepers", "list", "Returns a list of housekeepers ### Group account support", "/getHousekeepers"),
	},
	{
		ID:         "get-housekeeping-status.list",
		Method:     "GET",
		Path:       "/getHousekeepingStatus",
		Summary:    "Returns the current date's housekeeping information The housekeeping status is calculated basing on the set of...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-housekeeping-status", "list", "Returns the current date's housekeeping information The housekeeping status is calculated basing on the set of...", "/getHousekeepingStatus"),
	},
	{
		ID:         "get-item.list",
		Method:     "GET",
		Path:       "/getItem",
		Summary:    "Gets the details for the one itemID<br /> <sup>1</sup> only if data.stockInventory = true<br> <sup>2</sup> Taxes,...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-item", "list", "Gets the details for the one itemID<br /> <sup>1</sup> only if data.stockInventory = true<br> <sup>2</sup> Taxes,...", "/getItem"),
	},
	{
		ID:         "get-item-categories.list",
		Method:     "GET",
		Path:       "/getItemCategories",
		Summary:    "Gets the item category list",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-item-categories", "list", "Gets the item category list", "/getItemCategories"),
	},
	{
		ID:         "get-items.list",
		Method:     "GET",
		Path:       "/getItems",
		Summary:    "Gets all the items and their prices the hotel has created in myfrontdesk<br> <sup>1</sup> only if...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-items", "list", "Gets all the items and their prices the hotel has created in myfrontdesk<br> <sup>1</sup> only if...", "/getItems"),
	},
	{
		ID:         "get-package-names.list",
		Method:     "GET",
		Path:       "/getPackageNames",
		Summary:    "Return a list of billing package names for a property",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-package-names", "list", "Return a list of billing package names for a property", "/getPackageNames"),
	},
	{
		ID:         "get-packages.list",
		Method:     "GET",
		Path:       "/getPackages",
		Summary:    "This efficient method allows you to retrieve the collection of packages associated with a property. Packages here...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-packages", "list", "This efficient method allows you to retrieve the collection of packages associated with a property. Packages here...", "/getPackages"),
	},
	{
		ID:         "get-payment-methods.list",
		Method:     "GET",
		Path:       "/getPaymentMethods",
		Summary:    "Get a list of active methods for a property, or list of properties",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-payment-methods", "list", "Get a list of active methods for a property, or list of properties", "/getPaymentMethods"),
	},
	{
		ID:         "get-payments-capabilities.list",
		Method:     "GET",
		Path:       "/getPaymentsCapabilities",
		Summary:    "Lists the payment capabilities of a given property",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-payments-capabilities", "list", "Lists the payment capabilities of a given property", "/getPaymentsCapabilities"),
	},
	{
		ID:         "get-rate.list",
		Method:     "GET",
		Path:       "/getRate",
		Summary:    "Returns the rate of the room type selected, based on the provided parameters",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-rate", "list", "Returns the rate of the room type selected, based on the provided parameters", "/getRate"),
	},
	{
		ID:         "get-rate-jobs.list",
		Method:     "GET",
		Path:       "/getRateJobs",
		Summary:    "Returns a list of Rate Jobs. Rate jobs are only returned within 7 days of creation, after 7 days they will not be...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-rate-jobs", "list", "Returns a list of Rate Jobs. Rate jobs are only returned within 7 days of creation, after 7 days they will not be...", "/getRateJobs"),
	},
	{
		ID:         "get-rate-plans.list",
		Method:     "GET",
		Path:       "/getRatePlans",
		Summary:    "Returns the rates of the room type or promo code selected, based on the provided parameters. If no parameters are...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-rate-plans", "list", "Returns the rates of the room type or promo code selected, based on the provided parameters. If no parameters are...", "/getRatePlans"),
	},
	{
		ID:         "get-reservation.list",
		Method:     "GET",
		Path:       "/getReservation",
		Summary:    "Returns information on a booking specified by the reservationID parameter",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-reservation", "list", "Returns information on a booking specified by the reservationID parameter", "/getReservation"),
	},
	{
		ID:         "get-reservation-assignments.list",
		Method:     "GET",
		Path:       "/getReservationAssignments",
		Summary:    "Returns a list of rooms/reservations assigned for a selected date.",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-reservation-assignments", "list", "Returns a list of rooms/reservations assigned for a selected date.", "/getReservationAssignments"),
	},
	{
		ID:         "get-reservation-notes.list",
		Method:     "GET",
		Path:       "/getReservationNotes",
		Summary:    "Retrieves reservation notes based on parameters",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-reservation-notes", "list", "Retrieves reservation notes based on parameters", "/getReservationNotes"),
	},
	{
		ID:         "get-reservation-room-details.list",
		Method:     "GET",
		Path:       "/getReservationRoomDetails",
		Summary:    "Returns information about particular room in reservation by its subReservationID",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-reservation-room-details", "list", "Returns information about particular room in reservation by its subReservationID", "/getReservationRoomDetails"),
	},
	{
		ID:         "get-reservations.list",
		Method:     "GET",
		Path:       "/getReservations",
		Summary:    "Returns a list of reservations that matched the filters criteria.<br /> Please note that some reservations...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-reservations", "list", "Returns a list of reservations that matched the filters criteria.<br /> Please note that some reservations...", "/getReservations"),
	},
	{
		ID:         "get-reservations-with-rate-details.list",
		Method:     "GET",
		Path:       "/getReservationsWithRateDetails",
		Summary:    "Returns a list of reservations with added information regarding booked rates and sources.<br /> Please note that...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-reservations-with-rate-details", "list", "Returns a list of reservations with added information regarding booked rates and sources.<br /> Please note that...", "/getReservationsWithRateDetails"),
	},
	{
		ID:         "get-room-blocks.list",
		Method:     "GET",
		Path:       "/getRoomBlocks",
		Summary:    "Returns a list of all room blocks considering the informed parameters.",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-room-blocks", "list", "Returns a list of all room blocks considering the informed parameters.", "/getRoomBlocks"),
	},
	{
		ID:         "get-room-types.list",
		Method:     "GET",
		Path:       "/getRoomTypes",
		Summary:    "Returns a list of room types filtered by the selected parameters ### Group account support",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-room-types", "list", "Returns a list of room types filtered by the selected parameters ### Group account support", "/getRoomTypes"),
	},
	{
		ID:         "get-rooms.list",
		Method:     "GET",
		Path:       "/getRooms",
		Summary:    "Returns a list of all rooms considering the informed parameters. If Check-in/out dates are sent, only unassigned...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-rooms", "list", "Returns a list of all rooms considering the informed parameters. If Check-in/out dates are sent, only unassigned...", "/getRooms"),
	},
	{
		ID:         "get-rooms-fees-and-taxes.list",
		Method:     "GET",
		Path:       "/getRoomsFeesAndTaxes",
		Summary:    "Get applicable fees and tax to a booking. This is meant to be used on checkout to display to the guest.",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-rooms-fees-and-taxes", "list", "Get applicable fees and tax to a booking. This is meant to be used on checkout to display to the guest.", "/getRoomsFeesAndTaxes"),
	},
	{
		ID:         "get-rooms-unassigned.list",
		Method:     "GET",
		Path:       "/getRoomsUnassigned",
		Summary:    "Returns a list of unassigned rooms in the property. Call is alias of [getRooms](#api-Room-getRooms). Please check...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-rooms-unassigned", "list", "Returns a list of unassigned rooms in the property. Call is alias of [getRooms](#api-Room-getRooms). Please check...", "/getRoomsUnassigned"),
	},
	{
		ID:         "get-sources.list",
		Method:     "GET",
		Path:       "/getSources",
		Summary:    "Gets available property sources",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-sources", "list", "Gets available property sources", "/getSources"),
	},
	{
		ID:         "get-taxes-and-fees.list",
		Method:     "GET",
		Path:       "/getTaxesAndFees",
		Summary:    "Returns the taxes and fees set for the property. Read the [Rate-Based tax (Dynamic Tax)...",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-taxes-and-fees", "list", "Returns the taxes and fees set for the property. Read the [Rate-Based tax (Dynamic Tax)...", "/getTaxesAndFees"),
	},
	{
		ID:         "get-users.list",
		Method:     "GET",
		Path:       "/getUsers",
		Summary:    "Returns information on the properties' users ### Group account support",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-users", "list", "Returns information on the properties' users ### Group account support", "/getUsers"),
	},
	{
		ID:         "get-webhooks.list",
		Method:     "GET",
		Path:       "/getWebhooks",
		Summary:    "List webhooks for which the API client is subscribed to.",
		Positional: []string{},
		keywords:   codeOrchKeywords("get-webhooks", "list", "List webhooks for which the API client is subscribed to.", "/getWebhooks"),
	},
	{
		ID:         "list-allotment-block-notes.list",
		Method:     "GET",
		Path:       "/listAllotmentBlockNotes",
		Summary:    "List notes added to an allotment block",
		Positional: []string{},
		keywords:   codeOrchKeywords("list-allotment-block-notes", "list", "List notes added to an allotment block", "/listAllotmentBlockNotes"),
	},
	{
		ID:         "oauth.list",
		Method:     "GET",
		Path:       "/oauth/metadata",
		Summary:    "In the context of properties being distributed across multiple localizations, this endpoint serves to retrieve the...",
		Positional: []string{},
		keywords:   codeOrchKeywords("oauth", "list", "In the context of properties being distributed across multiple localizations, this endpoint serves to retrieve the...", "/oauth/metadata"),
	},
	{
		ID:         "patch-group.create",
		Method:     "POST",
		Path:       "/patchGroup",
		Summary:    "Updates an existing group with information provided. At least one information field is required for this call.",
		Positional: []string{},
		keywords:   codeOrchKeywords("patch-group", "create", "Updates an existing group with information provided. At least one information field is required for this call.", "/patchGroup"),
	},
	{
		ID:         "patch-rate.create",
		Method:     "POST",
		Path:       "/patchRate",
		Summary:    "Update the rate of the room based on rateID selected, based on the provided parameters. You can make multiple rate...",
		Positional: []string{},
		keywords:   codeOrchKeywords("patch-rate", "create", "Update the rate of the room based on rateID selected, based on the provided parameters. You can make multiple rate...", "/patchRate"),
	},
	{
		ID:         "post-adjustment.create",
		Method:     "POST",
		Path:       "/postAdjustment",
		Summary:    "Adds an adjustment to a reservation",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-adjustment", "create", "Adds an adjustment to a reservation", "/postAdjustment"),
	},
	{
		ID:         "post-app-error.create",
		Method:     "POST",
		Path:       "/postAppError",
		Summary:    "Submit the error received by the hybrid integration from the partner to the MFD",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-app-error", "create", "Submit the error received by the hybrid integration from the partner to the MFD", "/postAppError"),
	},
	{
		ID:         "post-app-property-settings.create",
		Method:     "POST",
		Path:       "/postAppPropertySettings",
		Summary:    "Post app property settings",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-app-property-settings", "create", "Post app property settings", "/postAppPropertySettings"),
	},
	{
		ID:         "post-app-state.create",
		Method:     "POST",
		Path:       "/postAppState",
		Summary:    "Update app integration state for a property ID. <br /> This call is only available for third-party integration...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-app-state", "create", "Update app integration state for a property ID. <br /> This call is only available for third-party integration...", "/postAppState"),
	},
	{
		ID:         "post-charge.create",
		Method:     "POST",
		Path:       "/postCharge",
		Summary:    "Use a payment method to process a payment on a reservation, group profile, accounts receivable ledger, or house account.",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-charge", "create", "Use a payment method to process a payment on a reservation, group profile, accounts receivable ledger, or house account.", "/postCharge"),
	},
	{
		ID:         "post-credit-card.create",
		Method:     "POST",
		Path:       "/postCreditCard",
		Summary:    "Returns the rate of the room type selected, based on the provided parameters",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-credit-card", "create", "Returns the rate of the room type selected, based on the provided parameters", "/postCreditCard"),
	},
	{
		ID:         "post-custom-field.create",
		Method:     "POST",
		Path:       "/postCustomField",
		Summary:    "Sets custom fields. The call should only be made once to add the field to the system.",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-custom-field", "create", "Sets custom fields. The call should only be made once to add the field to the system.", "/postCustomField"),
	},
	{
		ID:         "post-custom-item.create",
		Method:     "POST",
		Path:       "/postCustomItem",
		Summary:    "Adds single, or multiple, custom items and their associated payments to a Reservation or House Account as a single...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-custom-item", "create", "Adds single, or multiple, custom items and their associated payments to a Reservation or House Account as a single...", "/postCustomItem"),
	},
	{
		ID:         "post-custom-payment-method.create",
		Method:     "POST",
		Path:       "/postCustomPaymentMethod",
		Summary:    "Add a Custom Payment Method to a property. This call does not allow to add Payment Methods: credit cards, bank...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-custom-payment-method", "create", "Add a Custom Payment Method to a property. This call does not allow to add Payment Methods: credit cards, bank...", "/postCustomPaymentMethod"),
	},
	{
		ID:         "post-email-schedule.create",
		Method:     "POST",
		Path:       "/postEmailSchedule",
		Summary:    "Creates a new email schedule for existing email template. Email template can be scheduled based on two parameters:...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-email-schedule", "create", "Creates a new email schedule for existing email template. Email template can be scheduled based on two parameters:...", "/postEmailSchedule"),
	},
	{
		ID:         "post-email-template.create",
		Method:     "POST",
		Path:       "/postEmailTemplate",
		Summary:    "Creates a new email template. See the full list of available language parameters <a...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-email-template", "create", "Creates a new email template. See the full list of available language parameters <a...", "/postEmailTemplate"),
	},
	{
		ID:         "post-file.create",
		Method:     "POST",
		Path:       "/postFile",
		Summary:    "Attaches a file to a hotel",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-file", "create", "Attaches a file to a hotel", "/postFile"),
	},
	{
		ID:         "post-government-receipt.create",
		Method:     "POST",
		Path:       "/postGovernmentReceipt",
		Summary:    "Add a Government Receipt to a Reservation or House Account",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-government-receipt", "create", "Add a Government Receipt to a Reservation or House Account", "/postGovernmentReceipt"),
	},
	{
		ID:         "post-group-note.create",
		Method:     "POST",
		Path:       "/postGroupNote",
		Summary:    "Adds a group note",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-group-note", "create", "Adds a group note", "/postGroupNote"),
	},
	{
		ID:         "post-guest.create",
		Method:     "POST",
		Path:       "/postGuest",
		Summary:    "Adds a guest to reservation as an additional guest.",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-guest", "create", "Adds a guest to reservation as an additional guest.", "/postGuest"),
	},
	{
		ID:         "post-guest-document.create",
		Method:     "POST",
		Path:       "/postGuestDocument",
		Summary:    "Attaches a document to a guest",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-guest-document", "create", "Attaches a document to a guest", "/postGuestDocument"),
	},
	{
		ID:         "post-guest-note.create",
		Method:     "POST",
		Path:       "/postGuestNote",
		Summary:    "Adds a guest note",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-guest-note", "create", "Adds a guest note", "/postGuestNote"),
	},
	{
		ID:         "post-guest-photo.create",
		Method:     "POST",
		Path:       "/postGuestPhoto",
		Summary:    "Attaches a photo to a guest",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-guest-photo", "create", "Attaches a photo to a guest", "/postGuestPhoto"),
	},
	{
		ID:         "post-guests-to-room.create",
		Method:     "POST",
		Path:       "/postGuestsToRoom",
		Summary:    "Assigns guest(s) to a room in a reservation and adds these guests as additional guests.",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-guests-to-room", "create", "Assigns guest(s) to a room in a reservation and adds these guests as additional guests.", "/postGuestsToRoom"),
	},
	{
		ID:         "post-housekeeper.create",
		Method:     "POST",
		Path:       "/postHousekeeper",
		Summary:    "Add New Housekeeper",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-housekeeper", "create", "Add New Housekeeper", "/postHousekeeper"),
	},
	{
		ID:         "post-housekeeping-assignment.create",
		Method:     "POST",
		Path:       "/postHousekeepingAssignment",
		Summary:    "Assign rooms (single or multiple) to an existing housekeeper",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-housekeeping-assignment", "create", "Assign rooms (single or multiple) to an existing housekeeper", "/postHousekeepingAssignment"),
	},
	{
		ID:         "post-housekeeping-status.create",
		Method:     "POST",
		Path:       "/postHousekeepingStatus",
		Summary:    "Switches the current date's housekeeping status for a specific room ID to either clean or dirty The housekeeping...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-housekeeping-status", "create", "Switches the current date's housekeeping status for a specific room ID to either clean or dirty The housekeeping...", "/postHousekeepingStatus"),
	},
	{
		ID:         "post-item.create",
		Method:     "POST",
		Path:       "/postItem",
		Summary:    "Adds an item either to a reservation or to a house account.",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-item", "create", "Adds an item either to a reservation or to a house account.", "/postItem"),
	},
	{
		ID:         "post-item-category.create",
		Method:     "POST",
		Path:       "/postItemCategory",
		Summary:    "Adds new items category",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-item-category", "create", "Adds new items category", "/postItemCategory"),
	},
	{
		ID:         "post-items-to-inventory.create",
		Method:     "POST",
		Path:       "/postItemsToInventory",
		Summary:    "Adds new items batch<br /> ¹ only if item.stockInventory = true<br />",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-items-to-inventory", "create", "Adds new items batch<br /> ¹ only if item.stockInventory = true<br />", "/postItemsToInventory"),
	},
	{
		ID:         "post-new-house-account.create",
		Method:     "POST",
		Path:       "/postNewHouseAccount",
		Summary:    "Add a new House Account",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-new-house-account", "create", "Add a new House Account", "/postNewHouseAccount"),
	},
	{
		ID:         "post-payment.create",
		Method:     "POST",
		Path:       "/postPayment",
		Summary:    "Add a payment to a specified reservation, house account, or group. If multiple IDs are provided, precedence is...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-payment", "create", "Add a payment to a specified reservation, house account, or group. If multiple IDs are provided, precedence is...", "/postPayment"),
	},
	{
		ID:         "post-reservation.create",
		Method:     "POST",
		Path:       "/postReservation",
		Summary:    "Adds a reservation to the selected property",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-reservation", "create", "Adds a reservation to the selected property", "/postReservation"),
	},
	{
		ID:         "post-reservation-document.create",
		Method:     "POST",
		Path:       "/postReservationDocument",
		Summary:    "Attaches a document to a reservation",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-reservation-document", "create", "Attaches a document to a reservation", "/postReservationDocument"),
	},
	{
		ID:         "post-reservation-note.create",
		Method:     "POST",
		Path:       "/postReservationNote",
		Summary:    "Adds a reservation note",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-reservation-note", "create", "Adds a reservation note", "/postReservationNote"),
	},
	{
		ID:         "post-room-assign.create",
		Method:     "POST",
		Path:       "/postRoomAssign",
		Summary:    "Assign/Reassign a room on a guest reservation",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-room-assign", "create", "Assign/Reassign a room on a guest reservation", "/postRoomAssign"),
	},
	{
		ID:         "post-room-block.create",
		Method:     "POST",
		Path:       "/postRoomBlock",
		Summary:    "Adds a room block to the selected property.",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-room-block", "create", "Adds a room block to the selected property.", "/postRoomBlock"),
	},
	{
		ID:         "post-room-check-in.create",
		Method:     "POST",
		Path:       "/postRoomCheckIn",
		Summary:    "Check-in a room already assigned for a guest",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-room-check-in", "create", "Check-in a room already assigned for a guest", "/postRoomCheckIn"),
	},
	{
		ID:         "post-room-check-out.create",
		Method:     "POST",
		Path:       "/postRoomCheckOut",
		Summary:    "Check-out a room already assigned for a guest. If all rooms are checked out, the reservation status will update...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-room-check-out", "create", "Check-out a room already assigned for a guest. If all rooms are checked out, the reservation status will update...", "/postRoomCheckOut"),
	},
	{
		ID:         "post-void-item.create",
		Method:     "POST",
		Path:       "/postVoidItem",
		Summary:    "Voids the itemID transaction on the specified Reservation ID, House Account ID, or Group. If payments were sent in...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-void-item", "create", "Voids the itemID transaction on the specified Reservation ID, House Account ID, or Group. If payments were sent in...", "/postVoidItem"),
	},
	{
		ID:         "post-void-payment.create",
		Method:     "POST",
		Path:       "/postVoidPayment",
		Summary:    "Voids a payment (using paymentID) to a specified reservation or house account.",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-void-payment", "create", "Voids a payment (using paymentID) to a specified reservation or house account.", "/postVoidPayment"),
	},
	{
		ID:         "post-webhook.create",
		Method:     "POST",
		Path:       "/postWebhook",
		Summary:    "Subscribe a webhook for a specified event. Read the [Webhooks...",
		Positional: []string{},
		keywords:   codeOrchKeywords("post-webhook", "create", "Subscribe a webhook for a specified event. Read the [Webhooks...", "/postWebhook"),
	},
	{
		ID:         "put-app-property-settings.create",
		Method:     "POST",
		Path:       "/putAppPropertySettings",
		Summary:    "Put app property settings",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-app-property-settings", "create", "Put app property settings", "/putAppPropertySettings"),
	},
	{
		ID:         "put-group.create",
		Method:     "POST",
		Path:       "/putGroup",
		Summary:    "Adds a group to the property. Please note that the default setting for 'Route to Group Folio' will be 'No,' and the...",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-group", "create", "Adds a group to the property. Please note that the default setting for 'Route to Group Folio' will be 'No,' and the...", "/putGroup"),
	},
	{
		ID:         "put-guest.update",
		Method:     "PUT",
		Path:       "/putGuest",
		Summary:    "Updates an existing guest with information provided. At least one information field is required for this call.",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-guest", "update", "Updates an existing guest with information provided. At least one information field is required for this call.", "/putGuest"),
	},
	{
		ID:         "put-guest-note.update",
		Method:     "PUT",
		Path:       "/putGuestNote",
		Summary:    "Updates an existing guest note.",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-guest-note", "update", "Updates an existing guest note.", "/putGuestNote"),
	},
	{
		ID:         "put-house-account-status.update",
		Method:     "PUT",
		Path:       "/putHouseAccountStatus",
		Summary:    "Change specific house account to either open or closed.",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-house-account-status", "update", "Change specific house account to either open or closed.", "/putHouseAccountStatus"),
	},
	{
		ID:         "put-housekeeper.update",
		Method:     "PUT",
		Path:       "/putHousekeeper",
		Summary:    "Edit Housekeeper Details",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-housekeeper", "update", "Edit Housekeeper Details", "/putHousekeeper"),
	},
	{
		ID:         "put-item-to-inventory.update",
		Method:     "PUT",
		Path:       "/putItemToInventory",
		Summary:    "Updates an item with information provided<br /> ¹ only if item.stockInventory = true<br />",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-item-to-inventory", "update", "Updates an item with information provided<br /> ¹ only if item.stockInventory = true<br />", "/putItemToInventory"),
	},
	{
		ID:         "put-rate.create",
		Method:     "POST",
		Path:       "/putRate",
		Summary:    "Update the rate of the room based on rateID selected, based on the provided parameters. You can make multiple rate...",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-rate", "create", "Update the rate of the room based on rateID selected, based on the provided parameters. You can make multiple rate...", "/putRate"),
	},
	{
		ID:         "put-reservation.update",
		Method:     "PUT",
		Path:       "/putReservation",
		Summary:    "Updates a reservation, such as custom fields, estimated arrival time, room configuration and reservation status.",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-reservation", "update", "Updates a reservation, such as custom fields, estimated arrival time, room configuration and reservation status.", "/putReservation"),
	},
	{
		ID:         "put-reservation-note.update",
		Method:     "PUT",
		Path:       "/putReservationNote",
		Summary:    "Updates an existing reservation note.",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-reservation-note", "update", "Updates an existing reservation note.", "/putReservationNote"),
	},
	{
		ID:         "put-room-block.update",
		Method:     "PUT",
		Path:       "/putRoomBlock",
		Summary:    "Updates a room block.",
		Positional: []string{},
		keywords:   codeOrchKeywords("put-room-block", "update", "Updates a room block.", "/putRoomBlock"),
	},
	{
		ID:         "update-allotment-block.create",
		Method:     "POST",
		Path:       "/updateAllotmentBlock",
		Summary:    "Update an allotment block @apiQuery {Integer} propertyID Property ID",
		Positional: []string{},
		keywords:   codeOrchKeywords("update-allotment-block", "create", "Update an allotment block @apiQuery {Integer} propertyID Property ID", "/updateAllotmentBlock"),
	},
	{
		ID:         "update-allotment-block-notes.create",
		Method:     "POST",
		Path:       "/updateAllotmentBlockNotes",
		Summary:    "Update a note on an allotment block",
		Positional: []string{},
		keywords:   codeOrchKeywords("update-allotment-block-notes", "create", "Update a note on an allotment block", "/updateAllotmentBlockNotes"),
	},
	{
		ID:         "userinfo.list",
		Method:     "GET",
		Path:       "/userinfo",
		Summary:    "Returns information on user who authorized connection",
		Positional: []string{},
		keywords:   codeOrchKeywords("userinfo", "list", "Returns information on user who authorized connection", "/userinfo"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		out = append(out, map[string]any{
			"endpoint_id": r.ep.ID,
			"method":      r.ep.Method,
			"path":        r.ep.Path,
			"summary":     r.ep.Summary,
			"score":       r.score,
		})
	}
	data, _ := json.Marshal(map[string]any{"count": len(out), "results": out})
	return mcplib.NewToolResultText(string(data)), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call cloudbeds_search first)"), nil
	}

	var ep *codeOrchEndpoint
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			ep = &codeOrchEndpoints[i]
			break
		}
	}
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call cloudbeds_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok {
			path = strings.ReplaceAll(path, "{"+p+"}", fmt.Sprintf("%v", v))
			delete(params, p)
		}
	}

	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[k] = fmt.Sprintf("%v", v)
		}
	}

	var data json.RawMessage
	switch ep.Method {
	case "GET":
		data, err = c.Get(path, query)
	case "DELETE":
		data, _, err = c.Delete(path)
	default:
		body, mErr := json.Marshal(params)
		if mErr != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("marshaling body: %v", mErr)), nil
		}
		switch ep.Method {
		case "POST":
			data, _, err = c.Post(path, body)
		case "PUT":
			data, _, err = c.Put(path, body)
		case "PATCH":
			data, _, err = c.Patch(path, body)
		default:
			return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
		}
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}
