// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"cloudbeds-pp-cli/internal/cli"
	"cloudbeds-pp-cli/internal/client"
	"cloudbeds-pp-cli/internal/cliutil"
	"cloudbeds-pp-cli/internal/config"
	"cloudbeds-pp-cli/internal/mcp/cobratree"
	"cloudbeds-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Tables match resource names.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = fmt.Sprintf("%v", v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, fmt.Sprintf("%v", v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = fmt.Sprintf("%v", v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			data, err = c.Get(path, params)
		case "POST":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Post(path, body)
		case "PUT":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Put(path, body)
		case "PATCH":
			body, _ := json.Marshal(bodyArgs)
			data, _, err = c.Patch(path, body)
		case "DELETE":
			data, _, err = c.Delete(path)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export CLOUDBEDS_OAUTH2=<your-key>" +
					"\n      Run 'cloudbeds-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export CLOUDBEDS_OAUTH2=<your-key>" +
					"\n      Run 'cloudbeds-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export CLOUDBEDS_OAUTH2=<your-key>" +
					"\n      Run 'cloudbeds-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		// For GET responses, wrap bare arrays with count metadata
		if method == "GET" {
			trimmed := strings.TrimSpace(string(data))
			if len(trimmed) > 0 && trimmed[0] == '[' {
				var items []json.RawMessage
				if json.Unmarshal(data, &items) == nil {
					wrapped := map[string]any{
						"count": len(items),
						"items": items,
					}
					out, _ := json.Marshal(wrapped)
					return mcplib.NewToolResultText(string(out)), nil
				}
			}
		}
		return mcplib.NewToolResultText(string(data)), nil
	}
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "cloudbeds-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 30*time.Second, 0)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "cloudbeds-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate is an allowlist (SELECT or WITH only) applied AFTER stripping the
// leading whitespace, line comments, block comments, and semicolons that
// SQLite itself ignores before parsing. A naive HasPrefix check on a
// keyword blocklist is bypassable by prefixing the dangerous statement with
// "/* x */" or "-- x\n" — TrimSpace strips outer whitespace but does not
// understand SQL comment syntax. Combined with the empirical fact that
// modernc.org/sqlite's mode=ro does NOT block VACUUM INTO (writes a snapshot
// to a new file) or ATTACH DATABASE (opens a separate writable handle),
// such a bypass produces silent exfiltration to an attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	upper := strings.ToUpper(stripLeadingSQLNoise(query))
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, _ := rows.Columns()
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		rows.Scan(ptrs...)
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}

	data, _ := json.MarshalIndent(results, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "cloudbeds",
		"description": "<p> Welcome to the documentation for <strong>Cloudbeds API Version v1.3</strong>! If you are looking to learn how to...",
		"archetype":   "content",
		"tool_count":  115,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion cloudbeds-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "CLOUDBEDS_OAUTH2",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "access-token",
				"description": "Manage access token",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "append-custom-item",
				"description": "Manage append custom item",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "create-allotment-block",
				"description": "Manage create allotment block",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "create-allotment-block-notes",
				"description": "Manage create allotment block notes",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "delete-adjustment",
				"description": "Manage delete adjustment",
				"endpoints":   []string{"delete"},
			},
			{
				"name":        "delete-allotment-block",
				"description": "Manage delete allotment block",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "delete-app-property-settings",
				"description": "Manage delete app property settings",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "delete-guest-note",
				"description": "Manage delete guest note",
				"endpoints":   []string{"delete"},
			},
			{
				"name":        "delete-reservation-note",
				"description": "Manage delete reservation note",
				"endpoints":   []string{"delete"},
			},
			{
				"name":        "delete-room-block",
				"description": "Manage delete room block",
				"endpoints":   []string{"delete"},
			},
			{
				"name":        "delete-webhook",
				"description": "Manage delete webhook",
				"endpoints":   []string{"delete"},
			},
			{
				"name":        "get-allotment-blocks",
				"description": "Manage get allotment blocks",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-app-property-settings",
				"description": "Manage get app property settings",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-app-settings",
				"description": "Manage get app settings",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-app-state",
				"description": "Manage get app state",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-available-room-types",
				"description": "Manage get available room types",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-currency-settings",
				"description": "Manage get currency settings",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-custom-fields",
				"description": "Manage get custom fields",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-dashboard",
				"description": "Manage get dashboard",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-email-schedule",
				"description": "Manage get email schedule",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-email-templates",
				"description": "Manage get email templates",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-files",
				"description": "Manage get files",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-group-notes",
				"description": "Manage get group notes",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-groups",
				"description": "Manage get groups",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-guest",
				"description": "Manage get guest",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-guest-list",
				"description": "Manage get guest list",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-guest-notes",
				"description": "Manage get guest notes",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-guests-by-filter",
				"description": "Manage get guests by filter",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-guests-by-status",
				"description": "Manage get guests by status",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-guests-modified",
				"description": "Manage get guests modified",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-hotel-details",
				"description": "Manage get hotel details",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-hotels",
				"description": "Manage get hotels",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-house-account-list",
				"description": "Manage get house account list",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-housekeepers",
				"description": "Manage get housekeepers",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-housekeeping-status",
				"description": "Manage get housekeeping status",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-item",
				"description": "Manage get item",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-item-categories",
				"description": "Manage get item categories",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-items",
				"description": "Manage get items",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-package-names",
				"description": "Manage get package names",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-packages",
				"description": "Manage get packages",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-payment-methods",
				"description": "Manage get payment methods",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-payments-capabilities",
				"description": "Manage get payments capabilities",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-rate",
				"description": "Manage get rate",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-rate-jobs",
				"description": "Manage get rate jobs",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-rate-plans",
				"description": "Manage get rate plans",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-reservation",
				"description": "Manage get reservation",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-reservation-assignments",
				"description": "Manage get reservation assignments",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-reservation-notes",
				"description": "Manage get reservation notes",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-reservation-room-details",
				"description": "Manage get reservation room details",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-reservations",
				"description": "Manage get reservations",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-reservations-with-rate-details",
				"description": "Manage get reservations with rate details",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-room-blocks",
				"description": "Manage get room blocks",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-room-types",
				"description": "Manage get room types",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-rooms",
				"description": "Manage get rooms",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-rooms-fees-and-taxes",
				"description": "Manage get rooms fees and taxes",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "get-rooms-unassigned",
				"description": "Manage get rooms unassigned",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-sources",
				"description": "Manage get sources",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-taxes-and-fees",
				"description": "Manage get taxes and fees",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-users",
				"description": "Manage get users",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "get-webhooks",
				"description": "Manage get webhooks",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "list-allotment-block-notes",
				"description": "Manage list allotment block notes",
				"endpoints":   []string{"list"},
				"searchable":  true,
			},
			{
				"name":        "oauth",
				"description": "Manage oauth",
				"endpoints":   []string{"list"},
				"syncable":    true,
			},
			{
				"name":        "patch-group",
				"description": "Manage patch group",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "patch-rate",
				"description": "Manage patch rate",
				"endpoints":   []string{"create"},
			},
			{
				"name":        "post-adjustment",
				"description": "Manage post adjustment",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-app-error",
				"description": "Manage post app error",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-app-property-settings",
				"description": "Manage post app property settings",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-app-state",
				"description": "Manage post app state",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-charge",
				"description": "Manage post charge",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-credit-card",
				"description": "Manage post credit card",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-custom-field",
				"description": "Manage post custom field",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-custom-item",
				"description": "Manage post custom item",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-custom-payment-method",
				"description": "Manage post custom payment method",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-email-schedule",
				"description": "Manage post email schedule",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-email-template",
				"description": "Manage post email template",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-file",
				"description": "Manage post file",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-government-receipt",
				"description": "Manage post government receipt",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-group-note",
				"description": "Manage post group note",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-guest",
				"description": "Manage post guest",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-guest-document",
				"description": "Manage post guest document",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-guest-note",
				"description": "Manage post guest note",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-guest-photo",
				"description": "Manage post guest photo",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-guests-to-room",
				"description": "Manage post guests to room",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-housekeeper",
				"description": "Manage post housekeeper",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-housekeeping-assignment",
				"description": "Manage post housekeeping assignment",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-housekeeping-status",
				"description": "Manage post housekeeping status",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-item",
				"description": "Manage post item",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-item-category",
				"description": "Manage post item category",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-items-to-inventory",
				"description": "Manage post items to inventory",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-new-house-account",
				"description": "Manage post new house account",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-payment",
				"description": "Manage post payment",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-reservation",
				"description": "Manage post reservation",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-reservation-document",
				"description": "Manage post reservation document",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-reservation-note",
				"description": "Manage post reservation note",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-room-assign",
				"description": "Manage post room assign",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-room-block",
				"description": "Manage post room block",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-room-check-in",
				"description": "Manage post room check in",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-room-check-out",
				"description": "Manage post room check out",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-void-item",
				"description": "Manage post void item",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-void-payment",
				"description": "Manage post void payment",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "post-webhook",
				"description": "Manage post webhook",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "put-app-property-settings",
				"description": "Manage put app property settings",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "put-group",
				"description": "Manage put group",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "put-guest",
				"description": "Manage put guest",
				"endpoints":   []string{"update"},
				"searchable":  true,
			},
			{
				"name":        "put-guest-note",
				"description": "Manage put guest note",
				"endpoints":   []string{"update"},
				"searchable":  true,
			},
			{
				"name":        "put-house-account-status",
				"description": "Manage put house account status",
				"endpoints":   []string{"update"},
				"searchable":  true,
			},
			{
				"name":        "put-housekeeper",
				"description": "Manage put housekeeper",
				"endpoints":   []string{"update"},
				"searchable":  true,
			},
			{
				"name":        "put-item-to-inventory",
				"description": "Manage put item to inventory",
				"endpoints":   []string{"update"},
				"searchable":  true,
			},
			{
				"name":        "put-rate",
				"description": "Manage put rate",
				"endpoints":   []string{"create"},
			},
			{
				"name":        "put-reservation",
				"description": "Manage put reservation",
				"endpoints":   []string{"update"},
				"searchable":  true,
			},
			{
				"name":        "put-reservation-note",
				"description": "Manage put reservation note",
				"endpoints":   []string{"update"},
				"searchable":  true,
			},
			{
				"name":        "put-room-block",
				"description": "Manage put room block",
				"endpoints":   []string{"update"},
				"searchable":  true,
			},
			{
				"name":        "update-allotment-block",
				"description": "Manage update allotment block",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "update-allotment-block-notes",
				"description": "Manage update allotment block notes",
				"endpoints":   []string{"create"},
				"searchable":  true,
			},
			{
				"name":        "userinfo",
				"description": "Manage userinfo",
				"endpoints":   []string{"list"},
				"syncable":    true,
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the pagesize parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Stale-dirty rooms", "command": "housekeeping stale", "description": "Find rooms that have been dirty longer than a threshold so you can chase them before arrivals.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Today board", "command": "today", "description": "One-shot front-desk dashboard: arrivals, departures, in-house, unassigned, dirty rooms, today's ADR and occupancy.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Rate drift", "command": "rates drift", "description": "Show how rates moved over a window, by date, plan, and room type.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Occupancy trend", "command": "occupancy trend", "description": "Daily occupancy, ADR, and RevPAR series with week-over-week deltas.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Source mix", "command": "sources mix", "description": "Bookings, nights, and revenue by source (Booking.com, Expedia, Direct, Airbnb) over a window.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Unpaid upcoming", "command": "payments unpaid", "description": "Reservations arriving in the next N days with non-zero balance.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "No-show audit", "command": "reservations no-shows", "description": "No-show rate by source, room type, and lead-time bucket; flags repeat no-show guests.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Guest history search", "command": "guests search", "description": "Full-text search across guest name, email, phone, and notes; returns past stays with totals.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Mirror reconcile", "command": "reconcile", "description": "Compare local mirror to live API for a sampled window; emit a typed diff.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Reservation timeline", "command": "reservations timeline", "description": "Single-reservation forensic view: status changes, payments, notes, room assignments — chronological.", "rationale": "", "via": "mcp-command-mirror"},
			{"name": "Night audit pack", "command": "audit night", "description": "End-of-shift bundle: arrivals not checked-in, departures not checked-out, unbalanced folios, payments since last audit.", "rationale": "", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Stale-dirty rooms", "insight": ""},
			{"topic": "Today board", "insight": ""},
			{"topic": "Rate drift", "insight": ""},
			{"topic": "Occupancy trend", "insight": ""},
			{"topic": "Source mix", "insight": ""},
			{"topic": "Unpaid upcoming", "insight": ""},
			{"topic": "No-show audit", "insight": ""},
			{"topic": "Guest history search", "insight": ""},
			{"topic": "Mirror reconcile", "insight": ""},
			{"topic": "Reservation timeline", "insight": ""},
			{"topic": "Night audit pack", "insight": ""},
		},
	}
	data, _ := json.MarshalIndent(ctx, "", "  ")
	return mcplib.NewToolResultText(string(data)), nil
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
