// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetRoomsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyIDs string
	var flagRoomTypeID string
	var flagRoomTypeNameShort string
	var flagStartDate string
	var flagEndDate string
	var flagIncludeRoomRelations int
	var flagPageNumber int
	var flagPageSize int
	var flagSort string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-rooms",
		Short:       "Returns a list of all rooms considering the informed parameters. If Check-in/out dates are sent, only unassigned...",
		Long:        "Shortcut for 'get-rooms list'. Returns a list of all rooms considering the informed parameters. If Check-in/out dates are sent, only unassigned...",
		Example:     "  cloudbeds-pp-cli get-rooms",
		Annotations: map[string]string{"pp:endpoint": "get-rooms.list", "pp:method": "GET", "pp:path": "/getRooms", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getRooms"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-rooms", path, map[string]string{
				"propertyIDs":          fmt.Sprintf("%v", flagPropertyIDs),
				"roomTypeID":           fmt.Sprintf("%v", flagRoomTypeID),
				"roomTypeNameShort":    fmt.Sprintf("%v", flagRoomTypeNameShort),
				"startDate":            fmt.Sprintf("%v", flagStartDate),
				"endDate":              fmt.Sprintf("%v", flagEndDate),
				"includeRoomRelations": fmt.Sprintf("%v", flagIncludeRoomRelations),
				"pageNumber":           fmt.Sprintf("%v", flagPageNumber),
				"pageSize":             fmt.Sprintf("%v", flagPageSize),
				"sort":                 fmt.Sprintf("%v", flagSort),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyIDs, "property-i-ds", "", "Property ID list, comma-separated, i.e. 37,345,89")
	cmd.Flags().StringVar(&flagRoomTypeID, "room-type-id", "", "Room type ID, comma-separated, i.e. 37,345,89")
	cmd.Flags().StringVar(&flagRoomTypeNameShort, "room-type-name-short", "", "Room Type (short-version)")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Initial stay date. If sent, only returns unassigned rooms in this period. If not sent, will return all rooms...")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Final stay date. Necessary if startDate is sent.")
	cmd.Flags().IntVar(&flagIncludeRoomRelations, "include-room-relations", 0, "Determines whether room relations info should be included in the response")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 20, "Page size")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sorting rules, semicolon-separated. Format: `field[:direction]`, where `direction` is `asc` or `desc`, defaults to...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
