// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostReservationPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAdults string
	var bodyAllotmentBlockCode string
	var bodyCardToken string
	var bodyChildren string
	var bodyCustomFields string
	var bodyDateCreated string
	var bodyEndDate string
	var bodyEstimatedArrivalTime string
	var bodyGroupCode string
	var bodyGuestCountry string
	var bodyGuestEmail string
	var bodyGuestFirstName string
	var bodyGuestGender string
	var bodyGuestLastName string
	var bodyGuestPhone string
	var bodyGuestRequirements string
	var bodyGuestZip string
	var bodyPaymentAuthorizationCode string
	var bodyPaymentMethod string
	var bodyPromoCode string
	var bodyPropertyID string
	var bodyRooms string
	var bodySendEmailConfirmation bool
	var bodySourceID string
	var bodyStartDate string
	var bodyThirdPartyIdentifier string

	cmd := &cobra.Command{
		Use:         "post-reservation",
		Short:       "Adds a reservation to the selected property",
		Long:        "Shortcut for 'post-reservation create'. Adds a reservation to the selected property",
		Example:     "  cloudbeds-pp-cli post-reservation",
		Annotations: map[string]string{"pp:endpoint": "post-reservation.create", "pp:method": "POST", "pp:path": "/postReservation"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postReservation"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAdults != "" {
				var parsedAdults any
				if err := json.Unmarshal([]byte(bodyAdults), &parsedAdults); err != nil {
					return fmt.Errorf("parsing --adults JSON: %w", err)
				}
				body["adults"] = parsedAdults
			}
			if bodyAllotmentBlockCode != "" {
				body["allotmentBlockCode"] = bodyAllotmentBlockCode
			}
			if bodyCardToken != "" {
				body["cardToken"] = bodyCardToken
			}
			if bodyChildren != "" {
				var parsedChildren any
				if err := json.Unmarshal([]byte(bodyChildren), &parsedChildren); err != nil {
					return fmt.Errorf("parsing --children JSON: %w", err)
				}
				body["children"] = parsedChildren
			}
			if bodyCustomFields != "" {
				var parsedCustomFields any
				if err := json.Unmarshal([]byte(bodyCustomFields), &parsedCustomFields); err != nil {
					return fmt.Errorf("parsing --custom-fields JSON: %w", err)
				}
				body["customFields"] = parsedCustomFields
			}
			if bodyDateCreated != "" {
				body["dateCreated"] = bodyDateCreated
			}
			if bodyEndDate != "" {
				body["endDate"] = bodyEndDate
			}
			if bodyEstimatedArrivalTime != "" {
				body["estimatedArrivalTime"] = bodyEstimatedArrivalTime
			}
			if bodyGroupCode != "" {
				body["groupCode"] = bodyGroupCode
			}
			if bodyGuestCountry != "" {
				body["guestCountry"] = bodyGuestCountry
			}
			if bodyGuestEmail != "" {
				body["guestEmail"] = bodyGuestEmail
			}
			if bodyGuestFirstName != "" {
				body["guestFirstName"] = bodyGuestFirstName
			}
			if bodyGuestGender != "" {
				body["guestGender"] = bodyGuestGender
			}
			if bodyGuestLastName != "" {
				body["guestLastName"] = bodyGuestLastName
			}
			if bodyGuestPhone != "" {
				body["guestPhone"] = bodyGuestPhone
			}
			if bodyGuestRequirements != "" {
				var parsedGuestRequirements any
				if err := json.Unmarshal([]byte(bodyGuestRequirements), &parsedGuestRequirements); err != nil {
					return fmt.Errorf("parsing --guest-requirements JSON: %w", err)
				}
				body["guestRequirements"] = parsedGuestRequirements
			}
			if bodyGuestZip != "" {
				body["guestZip"] = bodyGuestZip
			}
			if bodyPaymentAuthorizationCode != "" {
				body["paymentAuthorizationCode"] = bodyPaymentAuthorizationCode
			}
			if bodyPaymentMethod != "" {
				body["paymentMethod"] = bodyPaymentMethod
			}
			if bodyPromoCode != "" {
				body["promoCode"] = bodyPromoCode
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyRooms != "" {
				var parsedRooms any
				if err := json.Unmarshal([]byte(bodyRooms), &parsedRooms); err != nil {
					return fmt.Errorf("parsing --rooms JSON: %w", err)
				}
				body["rooms"] = parsedRooms
			}
			if bodySendEmailConfirmation != false {
				body["sendEmailConfirmation"] = bodySendEmailConfirmation
			}
			if bodySourceID != "" {
				body["sourceID"] = bodySourceID
			}
			if bodyStartDate != "" {
				body["startDate"] = bodyStartDate
			}
			if bodyThirdPartyIdentifier != "" {
				body["thirdPartyIdentifier"] = bodyThirdPartyIdentifier
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAdults, "adults", "", "Array with number of adults")
	cmd.Flags().StringVar(&bodyAllotmentBlockCode, "allotment-block-code", "", "Allotment block code to add reservation to allotment block.")
	cmd.Flags().StringVar(&bodyCardToken, "card-token", "", "Credit Card identifier. Payment Method must be credit. This field should be filled with credit card identifier...")
	cmd.Flags().StringVar(&bodyChildren, "children", "", "Array with number of children")
	cmd.Flags().StringVar(&bodyCustomFields, "custom-fields", "", "Array with custom fields information")
	cmd.Flags().StringVar(&bodyDateCreated, "date-created", "", "Date reservation was made. Defaults to current date if omitted.")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "Check-Out date.")
	cmd.Flags().StringVar(&bodyEstimatedArrivalTime, "estimated-arrival-time", "", "Estimated Arrival Time, 24-hour format.")
	cmd.Flags().StringVar(&bodyGroupCode, "group-code", "", "Code from the Aggregate Allotment block the reservation will be added to.")
	cmd.Flags().StringVar(&bodyGuestCountry, "guest-country", "", "Valid ISO-Code for Country (2 characters)")
	cmd.Flags().StringVar(&bodyGuestEmail, "guest-email", "", "Guest email")
	cmd.Flags().StringVar(&bodyGuestFirstName, "guest-first-name", "", "First name of the guest")
	cmd.Flags().StringVar(&bodyGuestGender, "guest-gender", "", "Guest gender")
	cmd.Flags().StringVar(&bodyGuestLastName, "guest-last-name", "", "Last name of the guest")
	cmd.Flags().StringVar(&bodyGuestPhone, "guest-phone", "", "Guest main phone number")
	cmd.Flags().StringVar(&bodyGuestRequirements, "guest-requirements", "", "Object with guest requirements information.")
	cmd.Flags().StringVar(&bodyGuestZip, "guest-zip", "", "ZIP Code")
	cmd.Flags().StringVar(&bodyPaymentAuthorizationCode, "payment-authorization-code", "", "Transaction identifier. Payment Method must be credit. This field should be filled with transaction identifier...")
	cmd.Flags().StringVar(&bodyPaymentMethod, "payment-method", "", "Payment Method of choice.")
	cmd.Flags().StringVar(&bodyPromoCode, "promo-code", "", "Promotional code. Required for specials and packages that uses it. 'rateID' parameter required for using 'promoCode'.")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodyRooms, "rooms", "", "Array with quantity of rooms")
	cmd.Flags().BoolVar(&bodySendEmailConfirmation, "send-email-confirmation", true, "Send confirmation email to guest.")
	cmd.Flags().StringVar(&bodySourceID, "source-id", "", "The source ID for this reservation. Accepted formats:<br /> 's-{id}' for primary sources (no suffix), or<br />...")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "Check-In date.")
	cmd.Flags().StringVar(&bodyThirdPartyIdentifier, "third-party-identifier", "", "If it was received from a booking channel, this can be an identifier from that channel.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
