// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetGuestsByFilterPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyIDs string
	var flagStatus string
	var flagReservationID string
	var flagRoomID string
	var flagGuestName string
	var flagCheckInFrom string
	var flagCheckInTo string
	var flagCheckOutFrom string
	var flagCheckOutTo string

	cmd := &cobra.Command{
		Use:         "get-guests-by-filter",
		Short:       "Returns a list of guests matching the selected parameters ### Group account support",
		Long:        "Shortcut for 'get-guests-by-filter list'. Returns a list of guests matching the selected parameters ### Group account support",
		Example:     "  cloudbeds-pp-cli get-guests-by-filter --status example-value",
		Annotations: map[string]string{"pp:endpoint": "get-guests-by-filter.list", "pp:method": "GET", "pp:path": "/getGuestsByFilter", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("status") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "status")
			}
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"cancelled", "checked_out", "in_house", "not_checked_in"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getGuestsByFilter"
			params := map[string]string{}
			if flagPropertyIDs != "" {
				params["propertyIDs"] = fmt.Sprintf("%v", flagPropertyIDs)
			}
			if flagStatus != "" {
				params["status"] = fmt.Sprintf("%v", flagStatus)
			}
			if flagReservationID != "" {
				params["reservationID"] = fmt.Sprintf("%v", flagReservationID)
			}
			if flagRoomID != "" {
				params["roomID"] = fmt.Sprintf("%v", flagRoomID)
			}
			if flagGuestName != "" {
				params["guestName"] = fmt.Sprintf("%v", flagGuestName)
			}
			if flagCheckInFrom != "" {
				params["checkInFrom"] = fmt.Sprintf("%v", flagCheckInFrom)
			}
			if flagCheckInTo != "" {
				params["checkInTo"] = fmt.Sprintf("%v", flagCheckInTo)
			}
			if flagCheckOutFrom != "" {
				params["checkOutFrom"] = fmt.Sprintf("%v", flagCheckOutFrom)
			}
			if flagCheckOutTo != "" {
				params["checkOutTo"] = fmt.Sprintf("%v", flagCheckOutTo)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "get-guests-by-filter", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyIDs, "property-i-ds", "", "List of property IDs, comma-separated, i.e. 37,345,89")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Current guest status (one of: cancelled, checked_out, in_house, not_checked_in)")
	cmd.Flags().StringVar(&flagReservationID, "reservation-id", "", "Reservation id")
	cmd.Flags().StringVar(&flagRoomID, "room-id", "", "Room id")
	cmd.Flags().StringVar(&flagGuestName, "guest-name", "", "Guest name")
	cmd.Flags().StringVar(&flagCheckInFrom, "check-in-from", "", "Filters guests result to return only guests with check-in date range starting on this date")
	cmd.Flags().StringVar(&flagCheckInTo, "check-in-to", "", "Filters guests result to return only guests with check-in date range ending on this date")
	cmd.Flags().StringVar(&flagCheckOutFrom, "check-out-from", "", "Filters guests result to return only guests with check-out date range starting on this date")
	cmd.Flags().StringVar(&flagCheckOutTo, "check-out-to", "", "Filters guests result to return only guests with check-out date range ending on this date")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
