// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetReservationsWithRateDetailsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagResultsFrom string
	var flagResultsTo string
	var flagModifiedFrom string
	var flagModifiedTo string
	var flagSortByRecent bool
	var flagReservationID string
	var flagReservationCheckOutFrom string
	var flagReservationCheckOutTo string
	var flagIncludeDeleted bool
	var flagExcludeStatuses string
	var flagIncludeGuestsDetails bool
	var flagIncludeGuestRequirements bool
	var flagIncludeCustomFields bool
	var flagGuestID string
	var flagPageNumber int
	var flagPageSize int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-reservations-with-rate-details",
		Short:       "Returns a list of reservations with added information regarding booked rates and sources.<br /> Please note that...",
		Long:        "Shortcut for 'get-reservations-with-rate-details list'. Returns a list of reservations with added information regarding booked rates and sources.<br /> Please note that...",
		Example:     "  cloudbeds-pp-cli get-reservations-with-rate-details",
		Annotations: map[string]string{"pp:endpoint": "get-reservations-with-rate-details.list", "pp:method": "GET", "pp:path": "/getReservationsWithRateDetails", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getReservationsWithRateDetails"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-reservations-with-rate-details", path, map[string]string{
				"propertyID":               fmt.Sprintf("%v", flagPropertyID),
				"resultsFrom":              fmt.Sprintf("%v", flagResultsFrom),
				"resultsTo":                fmt.Sprintf("%v", flagResultsTo),
				"modifiedFrom":             fmt.Sprintf("%v", flagModifiedFrom),
				"modifiedTo":               fmt.Sprintf("%v", flagModifiedTo),
				"sortByRecent":             fmt.Sprintf("%v", flagSortByRecent),
				"reservationID":            fmt.Sprintf("%v", flagReservationID),
				"reservationCheckOutFrom":  fmt.Sprintf("%v", flagReservationCheckOutFrom),
				"reservationCheckOutTo":    fmt.Sprintf("%v", flagReservationCheckOutTo),
				"includeDeleted":           fmt.Sprintf("%v", flagIncludeDeleted),
				"excludeStatuses":          fmt.Sprintf("%v", flagExcludeStatuses),
				"includeGuestsDetails":     fmt.Sprintf("%v", flagIncludeGuestsDetails),
				"includeGuestRequirements": fmt.Sprintf("%v", flagIncludeGuestRequirements),
				"includeCustomFields":      fmt.Sprintf("%v", flagIncludeCustomFields),
				"guestID":                  fmt.Sprintf("%v", flagGuestID),
				"pageNumber":               fmt.Sprintf("%v", flagPageNumber),
				"pageSize":                 fmt.Sprintf("%v", flagPageSize),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&flagResultsFrom, "results-from", "", "Inferior limit datetime, used to filter reservations, based on booking date")
	cmd.Flags().StringVar(&flagResultsTo, "results-to", "", "Superior limit datetime, used to filter reservations, based on booking date. If it is not set, will return the...")
	cmd.Flags().StringVar(&flagModifiedFrom, "modified-from", "", "Superior limit datetime, used to filter reservations, based on modification date.")
	cmd.Flags().StringVar(&flagModifiedTo, "modified-to", "", "Superior limit datetime, used to filter reservations, based on modification date.")
	cmd.Flags().BoolVar(&flagSortByRecent, "sort-by-recent", false, "Sort response results by most recent action")
	cmd.Flags().StringVar(&flagReservationID, "reservation-id", "", "Reservation identifiers, comma-separated, i.e. 37,345,89, used to return transactions limited to the selected...")
	cmd.Flags().StringVar(&flagReservationCheckOutFrom, "reservation-check-out-from", "", "Superior limit datetime, used to filter reservations, based on reservation check-out date.")
	cmd.Flags().StringVar(&flagReservationCheckOutTo, "reservation-check-out-to", "", "Superior limit datetime, used to filter reservations, based on reservation check-out date.")
	cmd.Flags().BoolVar(&flagIncludeDeleted, "include-deleted", false, "Include deleted reservations")
	cmd.Flags().StringVar(&flagExcludeStatuses, "exclude-statuses", "", "List of statuses (separated by comma) to be excluded from search")
	cmd.Flags().BoolVar(&flagIncludeGuestsDetails, "include-guests-details", false, "If guests details should be included or not")
	cmd.Flags().BoolVar(&flagIncludeGuestRequirements, "include-guest-requirements", false, "Includes guest requirements data in the response. Requires `includeGuestsDetails=true`.")
	cmd.Flags().BoolVar(&flagIncludeCustomFields, "include-custom-fields", false, "If reservation custom fields should be included or not")
	cmd.Flags().StringVar(&flagGuestID, "guest-id", "", "Filters reservations with the supplied Guest ID (Including additional guests).")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "Results page size. Max = 100")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
