// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostWebhookPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAction string
	var bodyEndpointUrl string
	var bodyObject string
	var bodyPropertyID string

	cmd := &cobra.Command{
		Use:         "post-webhook",
		Short:       "Subscribe a webhook for a specified event. Read the [Webhooks...",
		Long:        "Shortcut for 'post-webhook create'. Subscribe a webhook for a specified event. Read the [Webhooks...",
		Example:     "  cloudbeds-pp-cli post-webhook",
		Annotations: map[string]string{"pp:endpoint": "post-webhook.create", "pp:method": "POST", "pp:path": "/postWebhook"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postWebhook"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAction != "" {
				body["action"] = bodyAction
			}
			if bodyEndpointUrl != "" {
				body["endpointUrl"] = bodyEndpointUrl
			}
			if bodyObject != "" {
				body["object"] = bodyObject
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAction, "action", "", "Event action")
	cmd.Flags().StringVar(&bodyEndpointUrl, "endpoint-url", "", "Endpoint URL")
	cmd.Flags().StringVar(&bodyObject, "object", "", "Event object")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
