// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostGovernmentReceiptPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAmount float64
	var bodyHouseAccountID string
	var bodyIdentifier string
	var bodyIssueDate string
	var bodyName string
	var bodyPropertyID string
	var bodyReservationID string
	var bodyUrl string

	cmd := &cobra.Command{
		Use:         "post-government-receipt",
		Short:       "Add a Government Receipt to a Reservation or House Account",
		Long:        "Shortcut for 'post-government-receipt create'. Add a Government Receipt to a Reservation or House Account",
		Example:     "  cloudbeds-pp-cli post-government-receipt",
		Annotations: map[string]string{"pp:endpoint": "post-government-receipt.create", "pp:method": "POST", "pp:path": "/postGovernmentReceipt"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postGovernmentReceipt"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAmount != 0.0 {
				body["amount"] = bodyAmount
			}
			if bodyHouseAccountID != "" {
				body["houseAccountID"] = bodyHouseAccountID
			}
			if bodyIdentifier != "" {
				body["identifier"] = bodyIdentifier
			}
			if bodyIssueDate != "" {
				body["issueDate"] = bodyIssueDate
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyReservationID != "" {
				body["reservationID"] = bodyReservationID
			}
			if bodyUrl != "" {
				body["url"] = bodyUrl
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().Float64Var(&bodyAmount, "amount", 0.0, "Value of posted document")
	cmd.Flags().StringVar(&bodyHouseAccountID, "house-account-id", "", "House Account identifier. It, or reservationID, is necessary.")
	cmd.Flags().StringVar(&bodyIdentifier, "identifier", "", "Receipt Identifier of document. If not sent, a random identifier will be generated.")
	cmd.Flags().StringVar(&bodyIssueDate, "issue-date", "", "Datetime of document emission, if not sent, current datetime will be assumed.")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name of the document. Will be used to describe document in MFD.")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property identifier to be updated")
	cmd.Flags().StringVar(&bodyReservationID, "reservation-id", "", "Reservation identifier. It, or houseAccountID, is necessary.")
	cmd.Flags().StringVar(&bodyUrl, "url", "", "URL for user to download document.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
