// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDeleteGuestNotePromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagGuestID string
	var flagNoteID string

	cmd := &cobra.Command{
		Use:         "delete-guest-note",
		Short:       "Archives an existing guest note.",
		Long:        "Shortcut for 'delete-guest-note delete'. Archives an existing guest note.",
		Example:     "  cloudbeds-pp-cli delete-guest-note --guest-id 550e8400-e29b-41d4-a716-446655440000 --note-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "delete-guest-note.delete", "pp:method": "DELETE", "pp:path": "/deleteGuestNote"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("guest-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "guest-id")
			}
			if !cmd.Flags().Changed("note-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "note-id")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/deleteGuestNote"
			data, _, err := c.Delete(path)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyDeleteError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&flagGuestID, "guest-id", "", "Guest ID")
	cmd.Flags().StringVar(&flagNoteID, "note-id", "", "Note ID")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
