// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostRoomAssignPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAdjustPrice bool
	var bodyNewRoomID string
	var bodyOldRoomID string
	var bodyOverrideRates bool
	var bodyPropertyID string
	var bodyReservationID string
	var bodyReservationRoomID string
	var bodyRoomTypeID string
	var bodySubReservationID string

	cmd := &cobra.Command{
		Use:         "post-room-assign",
		Short:       "Assign/Reassign a room on a guest reservation",
		Long:        "Shortcut for 'post-room-assign create'. Assign/Reassign a room on a guest reservation",
		Example:     "  cloudbeds-pp-cli post-room-assign",
		Annotations: map[string]string{"pp:endpoint": "post-room-assign.create", "pp:method": "POST", "pp:path": "/postRoomAssign"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postRoomAssign"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAdjustPrice != false {
				body["adjustPrice"] = bodyAdjustPrice
			}
			if bodyNewRoomID != "" {
				body["newRoomID"] = bodyNewRoomID
			}
			if bodyOldRoomID != "" {
				body["oldRoomID"] = bodyOldRoomID
			}
			if bodyOverrideRates != false {
				body["overrideRates"] = bodyOverrideRates
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyReservationID != "" {
				body["reservationID"] = bodyReservationID
			}
			if bodyReservationRoomID != "" {
				body["reservationRoomID"] = bodyReservationRoomID
			}
			if bodyRoomTypeID != "" {
				body["roomTypeID"] = bodyRoomTypeID
			}
			if bodySubReservationID != "" {
				body["subReservationID"] = bodySubReservationID
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&bodyAdjustPrice, "adjust-price", false, "If room assignment would result in an upcharge or discount, this parameter needs to be set to true to approve the...")
	cmd.Flags().StringVar(&bodyNewRoomID, "new-room-id", "", "Room ID of the room that will be assigned. Empty field must be sent if you want to unassign a room.")
	cmd.Flags().StringVar(&bodyOldRoomID, "old-room-id", "", "Room ID of the room that was assigned. Need to be provided in case of reassignment.")
	cmd.Flags().BoolVar(&bodyOverrideRates, "override-rates", false, "Deprecated. Please use adjustPrice instead. Setting overrideRates=true will have the opposite of the effect that the...")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodyReservationID, "reservation-id", "", "Reservation identifier")
	cmd.Flags().StringVar(&bodyReservationRoomID, "reservation-room-id", "", "Reservation room ID. Must be set if you want to unassign a room.")
	cmd.Flags().StringVar(&bodyRoomTypeID, "room-type-id", "", "Room Type ID of the room that will be assigned. Need to be provided in case of assignment.")
	cmd.Flags().StringVar(&bodySubReservationID, "sub-reservation-id", "", "Sub Reservation identifier")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
