// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostRoomBlockPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyEmail string
	var bodyEndDate string
	var bodyFirstName string
	var bodyLastName string
	var bodyLengthOfHoldInHours int
	var bodyPhone string
	var bodyPropertyID string
	var bodyRoomBlockReason string
	var bodyRoomBlockType string
	var bodyRooms string
	var bodyStartDate string

	cmd := &cobra.Command{
		Use:         "post-room-block",
		Short:       "Adds a room block to the selected property.",
		Long:        "Shortcut for 'post-room-block create'. Adds a room block to the selected property.",
		Example:     "  cloudbeds-pp-cli post-room-block",
		Annotations: map[string]string{"pp:endpoint": "post-room-block.create", "pp:method": "POST", "pp:path": "/postRoomBlock"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postRoomBlock"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyEmail != "" {
				body["email"] = bodyEmail
			}
			if bodyEndDate != "" {
				body["endDate"] = bodyEndDate
			}
			if bodyFirstName != "" {
				body["firstName"] = bodyFirstName
			}
			if bodyLastName != "" {
				body["lastName"] = bodyLastName
			}
			if bodyLengthOfHoldInHours != 0 {
				body["lengthOfHoldInHours"] = bodyLengthOfHoldInHours
			}
			if bodyPhone != "" {
				body["phone"] = bodyPhone
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyRoomBlockReason != "" {
				body["roomBlockReason"] = bodyRoomBlockReason
			}
			if bodyRoomBlockType != "" {
				body["roomBlockType"] = bodyRoomBlockType
			}
			if bodyRooms != "" {
				var parsedRooms any
				if err := json.Unmarshal([]byte(bodyRooms), &parsedRooms); err != nil {
					return fmt.Errorf("parsing --rooms JSON: %w", err)
				}
				body["rooms"] = parsedRooms
			}
			if bodyStartDate != "" {
				body["startDate"] = bodyStartDate
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyEmail, "email", "", "Email address - for courtesy hold updates")
	cmd.Flags().StringVar(&bodyEndDate, "end-date", "", "Room block end date")
	cmd.Flags().StringVar(&bodyFirstName, "first-name", "", "First name - for courtesy hold updates")
	cmd.Flags().StringVar(&bodyLastName, "last-name", "", "Last name - for courtesy hold updates")
	cmd.Flags().IntVar(&bodyLengthOfHoldInHours, "length-of-hold-in-hours", 0, "Length of hold in hours - for courtesy hold updates")
	cmd.Flags().StringVar(&bodyPhone, "phone", "", "Phone number - for courtesy hold updates")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodyRoomBlockReason, "room-block-reason", "", "Room block reason")
	cmd.Flags().StringVar(&bodyRoomBlockType, "room-block-type", "", "Room block type. ‘blocked’ - Room block. ‘out_of_service’ - Out of service block. 'courtesy_hold' - Courtesy...")
	cmd.Flags().StringVar(&bodyRooms, "rooms", "", "All rooms for room block. When multiple rooms are submitted they will be created under the same roomBlockID. For...")
	cmd.Flags().StringVar(&bodyStartDate, "start-date", "", "Room block start date")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
