// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetAllotmentBlocksPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagAllotmentBlockCode string
	var flagAllotmentBlockName string
	var flagGroupCode string
	var flagEventCode string
	var flagAllotmentBlockStatus string
	var flagAllotmentBlockType string
	var flagRoomTypeID string
	var flagPageSize int
	var flagPageNumber int
	var flagStartDate string
	var flagEndDate string
	var flagForUpdate bool
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-allotment-blocks",
		Short:       "Retrieve allotment blocks",
		Long:        "Shortcut for 'get-allotment-blocks list'. Retrieve allotment blocks",
		Example:     "  cloudbeds-pp-cli get-allotment-blocks --property-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "get-allotment-blocks.list", "pp:method": "GET", "pp:path": "/getAllotmentBlocks", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("property-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "property-id")
			}
			if cmd.Flags().Changed("allotment-block-status") {
				allowedAllotmentBlockStatus := []string{"definite", "tentative", "lead", "cancelled"}
				validAllotmentBlockStatus := false
				for _, v := range allowedAllotmentBlockStatus {
					if flagAllotmentBlockStatus == v {
						validAllotmentBlockStatus = true
						break
					}
				}
				if !validAllotmentBlockStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "allotment-block-status", flagAllotmentBlockStatus, allowedAllotmentBlockStatus)
				}
			}
			if cmd.Flags().Changed("allotment-block-type") {
				allowedAllotmentBlockType := []string{"aggregate", "allotment"}
				validAllotmentBlockType := false
				for _, v := range allowedAllotmentBlockType {
					if flagAllotmentBlockType == v {
						validAllotmentBlockType = true
						break
					}
				}
				if !validAllotmentBlockType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "allotment-block-type", flagAllotmentBlockType, allowedAllotmentBlockType)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getAllotmentBlocks"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-allotment-blocks", path, map[string]string{
				"propertyID":           fmt.Sprintf("%v", flagPropertyID),
				"allotmentBlockCode":   fmt.Sprintf("%v", flagAllotmentBlockCode),
				"allotmentBlockName":   fmt.Sprintf("%v", flagAllotmentBlockName),
				"groupCode":            fmt.Sprintf("%v", flagGroupCode),
				"eventCode":            fmt.Sprintf("%v", flagEventCode),
				"allotmentBlockStatus": fmt.Sprintf("%v", flagAllotmentBlockStatus),
				"allotmentBlockType":   fmt.Sprintf("%v", flagAllotmentBlockType),
				"roomTypeID":           fmt.Sprintf("%v", flagRoomTypeID),
				"pageSize":             fmt.Sprintf("%v", flagPageSize),
				"pageNumber":           fmt.Sprintf("%v", flagPageNumber),
				"startDate":            fmt.Sprintf("%v", flagStartDate),
				"endDate":              fmt.Sprintf("%v", flagEndDate),
				"forUpdate":            fmt.Sprintf("%v", flagForUpdate),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "Property ID (optional, by default all authorized properties will be included)")
	cmd.Flags().StringVar(&flagAllotmentBlockCode, "allotment-block-code", "", "Allotment block code")
	cmd.Flags().StringVar(&flagAllotmentBlockName, "allotment-block-name", "", "Allotment block name")
	cmd.Flags().StringVar(&flagGroupCode, "group-code", "", "A group profile code")
	cmd.Flags().StringVar(&flagEventCode, "event-code", "", "An event code")
	cmd.Flags().StringVar(&flagAllotmentBlockStatus, "allotment-block-status", "", "Allotment block status(es) (one of: definite, tentative, lead, cancelled)")
	cmd.Flags().StringVar(&flagAllotmentBlockType, "allotment-block-type", "", "The type of allotment block (one of: aggregate, allotment)")
	cmd.Flags().StringVar(&flagRoomTypeID, "room-type-id", "", "Filters allotment blocks with the supplied Room Type ID.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "Number of allotment blocks to return per page (min: 1, max: 100)")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 0, "Which page in the results to access")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Interval start date")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Interval end date")
	cmd.Flags().BoolVar(&flagForUpdate, "for-update", false, "If false (default) this will show the effective availability on each date. If true, will read raw availability from...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
