// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostChargePromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAccountsReceivableLedgerID string
	var bodyAmount string
	var bodyCardToken string
	var bodyCurrency string
	var bodyDescription string
	var bodyGroupID string
	var bodyHouseAccountID string
	var bodyIsDeposit bool
	var bodyPaymentMethodId string
	var bodyPropertyID string
	var bodyRedirectUrl string
	var bodyReservationID string

	cmd := &cobra.Command{
		Use:         "post-charge",
		Short:       "Use a payment method to process a payment on a reservation, group profile, accounts receivable ledger, or house account.",
		Long:        "Shortcut for 'post-charge create'. Use a payment method to process a payment on a reservation, group profile, accounts receivable ledger, or house account.",
		Example:     "  cloudbeds-pp-cli post-charge",
		Annotations: map[string]string{"pp:endpoint": "post-charge.create", "pp:method": "POST", "pp:path": "/postCharge"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postCharge"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAccountsReceivableLedgerID != "" {
				body["accountsReceivableLedgerID"] = bodyAccountsReceivableLedgerID
			}
			if bodyAmount != "" {
				body["amount"] = bodyAmount
			}
			if bodyCardToken != "" {
				body["cardToken"] = bodyCardToken
			}
			if bodyCurrency != "" {
				body["currency"] = bodyCurrency
			}
			if bodyDescription != "" {
				body["description"] = bodyDescription
			}
			if bodyGroupID != "" {
				body["groupID"] = bodyGroupID
			}
			if bodyHouseAccountID != "" {
				body["houseAccountID"] = bodyHouseAccountID
			}
			if bodyIsDeposit != false {
				body["isDeposit"] = bodyIsDeposit
			}
			if bodyPaymentMethodId != "" {
				body["paymentMethodId"] = bodyPaymentMethodId
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyRedirectUrl != "" {
				body["redirectUrl"] = bodyRedirectUrl
			}
			if bodyReservationID != "" {
				body["reservationID"] = bodyReservationID
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAccountsReceivableLedgerID, "accounts-receivable-ledger-id", "", "Accounts Receivable Ledger ID")
	cmd.Flags().StringVar(&bodyAmount, "amount", "", "Amount to charge")
	cmd.Flags().StringVar(&bodyCardToken, "card-token", "", "cardToken provided by Cloudbeds vault")
	cmd.Flags().StringVar(&bodyCurrency, "currency", "", "Currency to charge")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Description of the payment to display on folio")
	cmd.Flags().StringVar(&bodyGroupID, "group-id", "", "Group ID")
	cmd.Flags().StringVar(&bodyHouseAccountID, "house-account-id", "", "House Account ID")
	cmd.Flags().BoolVar(&bodyIsDeposit, "is-deposit", false, "determine if this payment is a deposit (default: false)")
	cmd.Flags().StringVar(&bodyPaymentMethodId, "payment-method-id", "", "Payment method UUID")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property id")
	cmd.Flags().StringVar(&bodyRedirectUrl, "redirect-url", "", "client will be redirected to this page after he completed 3ds challenge. User will be redirected with HTTP get...")
	cmd.Flags().StringVar(&bodyReservationID, "reservation-id", "", "Reservation ID")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
