// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAccessTokenPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyClientId string
	var bodyClientSecret string
	var bodyCode string
	var bodyGrantType string
	var bodyRedirectUri string
	var bodyRefreshToken string

	cmd := &cobra.Command{
		Use:         "access-token",
		Short:       "Query the authorization server for an access token used to access property resources.</br> If the automatic delivery...",
		Long:        "Shortcut for 'access-token create'. Query the authorization server for an access token used to access property resources.</br> If the automatic delivery...",
		Example:     "  cloudbeds-pp-cli access-token",
		Annotations: map[string]string{"pp:endpoint": "access-token.create", "pp:method": "POST", "pp:path": "/access_token"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/access_token"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyClientId != "" {
				body["client_id"] = bodyClientId
			}
			if bodyClientSecret != "" {
				body["client_secret"] = bodyClientSecret
			}
			if bodyCode != "" {
				body["code"] = bodyCode
			}
			if bodyGrantType != "" {
				body["grant_type"] = bodyGrantType
			}
			if bodyRedirectUri != "" {
				body["redirect_uri"] = bodyRedirectUri
			}
			if bodyRefreshToken != "" {
				body["refresh_token"] = bodyRefreshToken
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyClientId, "client-id", "", "The client identifier. Each client must be provisioned an identifier.")
	cmd.Flags().StringVar(&bodyClientSecret, "client-secret", "", "The client secret. Each client must be provisioned a secret.")
	cmd.Flags().StringVar(&bodyCode, "code", "", "An authorization code provisioned by /oauth (Required for grant type 'authorization_code' and...")
	cmd.Flags().StringVar(&bodyGrantType, "grant-type", "", "The OAuth2 grant type.")
	cmd.Flags().StringVar(&bodyRedirectUri, "redirect-uri", "", "The client pre-configured redirect URI. (Required for grant type 'authorization_code' and...")
	cmd.Flags().StringVar(&bodyRefreshToken, "refresh-token", "", "A refresh token to renew an access_token (Required for grant type 'refresh_token' only).")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
