// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetFilesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagGroupCode string
	var flagSortBy string
	var flagOrderBy string
	var flagName string
	var flagPageNumber int
	var flagPageSize int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-files",
		Short:       "Returns a list of files attached to a hotel or group profile, ordered by creation date",
		Long:        "Shortcut for 'get-files list'. Returns a list of files attached to a hotel or group profile, ordered by creation date",
		Example:     "  cloudbeds-pp-cli get-files",
		Annotations: map[string]string{"pp:endpoint": "get-files.list", "pp:method": "GET", "pp:path": "/getFiles", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("sort-by") {
				allowedSortBy := []string{"name", "type", "source", "date"}
				validSortBy := false
				for _, v := range allowedSortBy {
					if flagSortBy == v {
						validSortBy = true
						break
					}
				}
				if !validSortBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-by", flagSortBy, allowedSortBy)
				}
			}
			if cmd.Flags().Changed("order-by") {
				allowedOrderBy := []string{"desc", "asc"}
				validOrderBy := false
				for _, v := range allowedOrderBy {
					if flagOrderBy == v {
						validOrderBy = true
						break
					}
				}
				if !validOrderBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order-by", flagOrderBy, allowedOrderBy)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getFiles"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-files", path, map[string]string{
				"propertyID": fmt.Sprintf("%v", flagPropertyID),
				"groupCode":  fmt.Sprintf("%v", flagGroupCode),
				"sortBy":     fmt.Sprintf("%v", flagSortBy),
				"orderBy":    fmt.Sprintf("%v", flagOrderBy),
				"name":       fmt.Sprintf("%v", flagName),
				"pageNumber": fmt.Sprintf("%v", flagPageNumber),
				"pageSize":   fmt.Sprintf("%v", flagPageSize),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&flagGroupCode, "group-code", "", "The group code, if the files are to be fetched from a group profile")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "date", "Sort By parameter (one of: name, type, source, date)")
	cmd.Flags().StringVar(&flagOrderBy, "order-by", "desc", "Order response in DESCending or ASCending order, used together with sortBy (one of: desc, asc)")
	cmd.Flags().StringVar(&flagName, "name", "", "Filter filess by name. Include only with names containing specified string")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "Results page size. Max = 100")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
