// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostPaymentPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAmount float64
	var bodyCardType string
	var bodyDescription string
	var bodyGroupCode string
	var bodyHouseAccountID string
	var bodyIsDeposit bool
	var bodyPropertyID string
	var bodyReservationID string
	var bodySubReservationID string
	var bodyType string

	cmd := &cobra.Command{
		Use:         "post-payment",
		Short:       "Add a payment to a specified reservation, house account, or group. If multiple IDs are provided, precedence is...",
		Long:        "Shortcut for 'post-payment create'. Add a payment to a specified reservation, house account, or group. If multiple IDs are provided, precedence is...",
		Example:     "  cloudbeds-pp-cli post-payment",
		Annotations: map[string]string{"pp:endpoint": "post-payment.create", "pp:method": "POST", "pp:path": "/postPayment"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postPayment"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAmount != 0.0 {
				body["amount"] = bodyAmount
			}
			if bodyCardType != "" {
				body["cardType"] = bodyCardType
			}
			if bodyDescription != "" {
				body["description"] = bodyDescription
			}
			if bodyGroupCode != "" {
				body["groupCode"] = bodyGroupCode
			}
			if bodyHouseAccountID != "" {
				body["houseAccountID"] = bodyHouseAccountID
			}
			if bodyIsDeposit != false {
				body["isDeposit"] = bodyIsDeposit
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyReservationID != "" {
				body["reservationID"] = bodyReservationID
			}
			if bodySubReservationID != "" {
				body["subReservationID"] = bodySubReservationID
			}
			if bodyType != "" {
				body["type"] = bodyType
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().Float64Var(&bodyAmount, "amount", 0.0, "Amount paid on this transaction")
	cmd.Flags().StringVar(&bodyCardType, "card-type", "", "If type = credit, cardType is necessary. Allowed values are property based, but possible strings are:...")
	cmd.Flags().StringVar(&bodyDescription, "description", "", "Note to be added to payment")
	cmd.Flags().StringVar(&bodyGroupCode, "group-code", "", "Group Code. Required if neither reservationID nor houseAccountID is sent")
	cmd.Flags().StringVar(&bodyHouseAccountID, "house-account-id", "", "House Account identifier is necessary if reservationID not sent")
	cmd.Flags().BoolVar(&bodyIsDeposit, "is-deposit", false, "determine if this payment is a deposit (default: false)")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodyReservationID, "reservation-id", "", "Reservation identifier")
	cmd.Flags().StringVar(&bodySubReservationID, "sub-reservation-id", "", "The Sub Reservation identifier. reservationID is still mandatory if subReservationID is sent.")
	cmd.Flags().StringVar(&bodyType, "type", "", "Payment type. Use the call [getPaymentMethods](#api-Payment-getPaymentMethods) to get the properties enabled payment...")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
