// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPutReservationPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAllotmentBlockCode string
	var bodyCheckoutDate string
	var bodyCustomFields string
	var bodyDateCreated string
	var bodyEstimatedArrivalTime string
	var bodyEventCode string
	var bodyPropertyID string
	var bodyReservationID string
	var bodyRooms string
	var bodySendStatusChangeEmail bool
	var bodyStatus string

	cmd := &cobra.Command{
		Use:         "put-reservation",
		Short:       "Updates a reservation, such as custom fields, estimated arrival time, room configuration and reservation status.",
		Long:        "Shortcut for 'put-reservation update'. Updates a reservation, such as custom fields, estimated arrival time, room configuration and reservation status.",
		Example:     "  cloudbeds-pp-cli put-reservation",
		Annotations: map[string]string{"pp:endpoint": "put-reservation.update", "pp:method": "PUT", "pp:path": "/putReservation"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/putReservation"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAllotmentBlockCode != "" {
				body["allotmentBlockCode"] = bodyAllotmentBlockCode
			}
			if bodyCheckoutDate != "" {
				body["checkoutDate"] = bodyCheckoutDate
			}
			if bodyCustomFields != "" {
				var parsedCustomFields any
				if err := json.Unmarshal([]byte(bodyCustomFields), &parsedCustomFields); err != nil {
					return fmt.Errorf("parsing --custom-fields JSON: %w", err)
				}
				body["customFields"] = parsedCustomFields
			}
			if bodyDateCreated != "" {
				body["dateCreated"] = bodyDateCreated
			}
			if bodyEstimatedArrivalTime != "" {
				body["estimatedArrivalTime"] = bodyEstimatedArrivalTime
			}
			if bodyEventCode != "" {
				body["eventCode"] = bodyEventCode
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyReservationID != "" {
				body["reservationID"] = bodyReservationID
			}
			if bodyRooms != "" {
				var parsedRooms any
				if err := json.Unmarshal([]byte(bodyRooms), &parsedRooms); err != nil {
					return fmt.Errorf("parsing --rooms JSON: %w", err)
				}
				body["rooms"] = parsedRooms
			}
			if bodySendStatusChangeEmail != false {
				body["sendStatusChangeEmail"] = bodySendStatusChangeEmail
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			data, _, err := c.Put(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAllotmentBlockCode, "allotment-block-code", "", "Allotment block code to link the reservation to. Send null to unlink. If provided along with eventCode, the...")
	cmd.Flags().StringVar(&bodyCheckoutDate, "checkout-date", "", "Update the checkoutDate across the whole reservation")
	cmd.Flags().StringVar(&bodyCustomFields, "custom-fields", "", "Array with custom fields information")
	cmd.Flags().StringVar(&bodyDateCreated, "date-created", "", "Date reservation was made. Do not change if omitted.")
	cmd.Flags().StringVar(&bodyEstimatedArrivalTime, "estimated-arrival-time", "", "Estimated Arrival Time, 24-hour format.")
	cmd.Flags().StringVar(&bodyEventCode, "event-code", "", "Event (group profile) code to link the reservation to. Send null to unlink. When sent without allotmentBlockCode,...")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodyReservationID, "reservation-id", "", "Reservation Unique Identifier, one reservation ID per call.")
	cmd.Flags().StringVar(&bodyRooms, "rooms", "", "Array with rooms information to change accommodations assigned to the reservation")
	cmd.Flags().BoolVar(&bodySendStatusChangeEmail, "send-status-change-email", false, "Send email on reservation status change to property and guest.")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Reservation status<br /> 'confirmed' - Reservation is confirmed<br /> 'not_confirmed' - Reservation not passed...")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
