// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAppendCustomItemPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyGroupCode string
	var bodyGuestID string
	var bodyGuestName string
	var bodyHouseAccountID string
	var bodyItemPaid bool
	var bodyItems string
	var bodyPayments string
	var bodyPropertyID string
	var bodyReferenceID string
	var bodyReservationID string
	var bodyRoomID string
	var bodySaleDate string
	var bodySubReservationID string

	cmd := &cobra.Command{
		Use:         "append-custom-item",
		Short:       "Append single, or multiple, custom items and their associated payments to an existing one in a Reservation, House...",
		Long:        "Shortcut for 'append-custom-item create'. Append single, or multiple, custom items and their associated payments to an existing one in a Reservation, House...",
		Example:     "  cloudbeds-pp-cli append-custom-item",
		Annotations: map[string]string{"pp:endpoint": "append-custom-item.create", "pp:method": "POST", "pp:path": "/appendCustomItem"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/appendCustomItem"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyGroupCode != "" {
				body["groupCode"] = bodyGroupCode
			}
			if bodyGuestID != "" {
				body["guestID"] = bodyGuestID
			}
			if bodyGuestName != "" {
				body["guestName"] = bodyGuestName
			}
			if bodyHouseAccountID != "" {
				body["houseAccountID"] = bodyHouseAccountID
			}
			if bodyItemPaid != false {
				body["itemPaid"] = bodyItemPaid
			}
			if bodyItems != "" {
				var parsedItems any
				if err := json.Unmarshal([]byte(bodyItems), &parsedItems); err != nil {
					return fmt.Errorf("parsing --items JSON: %w", err)
				}
				body["items"] = parsedItems
			}
			if bodyPayments != "" {
				var parsedPayments any
				if err := json.Unmarshal([]byte(bodyPayments), &parsedPayments); err != nil {
					return fmt.Errorf("parsing --payments JSON: %w", err)
				}
				body["payments"] = parsedPayments
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyReferenceID != "" {
				body["referenceID"] = bodyReferenceID
			}
			if bodyReservationID != "" {
				body["reservationID"] = bodyReservationID
			}
			if bodyRoomID != "" {
				body["roomID"] = bodyRoomID
			}
			if bodySaleDate != "" {
				body["saleDate"] = bodySaleDate
			}
			if bodySubReservationID != "" {
				body["subReservationID"] = bodySubReservationID
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyGroupCode, "group-code", "", "Group code. Required if no reservationID or houseAccountID is provided.")
	cmd.Flags().StringVar(&bodyGuestID, "guest-id", "", "Guest identifier")
	cmd.Flags().StringVar(&bodyGuestName, "guest-name", "", "(Ignored if guestID exist)")
	cmd.Flags().StringVar(&bodyHouseAccountID, "house-account-id", "", "House Account identifier. Required if no reservationID or groupCode is provided.")
	cmd.Flags().BoolVar(&bodyItemPaid, "item-paid", false, "If the item is already paid. Note: If set to true, a payment in cash will be registered for the total value of the...")
	cmd.Flags().StringVar(&bodyItems, "items", "", "list of items will be posted")
	cmd.Flags().StringVar(&bodyPayments, "payments", "", "list of payments If the item is already paid")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodyReferenceID, "reference-id", "", "partner's transaction reference. If exist then Cloudbeds will prevent adding of duplicates")
	cmd.Flags().StringVar(&bodyReservationID, "reservation-id", "", "Reservation identifier. Required if no houseAccountID or groupCode is provided.")
	cmd.Flags().StringVar(&bodyRoomID, "room-id", "", "Room identifier (Ignored if subReservationID exist)")
	cmd.Flags().StringVar(&bodySaleDate, "sale-date", "", "Posting date. Defaults to now.")
	cmd.Flags().StringVar(&bodySubReservationID, "sub-reservation-id", "", "Sub Reservation identifier")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
