// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newListAllotmentBlockNotesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagAllotmentBlockCode string
	var flagStatus string
	var flagPageNumber int
	var flagPageSize int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "list-allotment-block-notes",
		Short:       "List notes added to an allotment block",
		Long:        "Shortcut for 'list-allotment-block-notes list'. List notes added to an allotment block",
		Example:     "  cloudbeds-pp-cli list-allotment-block-notes --property-id 550e8400-e29b-41d4-a716-446655440000 --allotment-block-code example-value",
		Annotations: map[string]string{"pp:endpoint": "list-allotment-block-notes.list", "pp:method": "GET", "pp:path": "/listAllotmentBlockNotes", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("property-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "property-id")
			}
			if !cmd.Flags().Changed("allotment-block-code") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "allotment-block-code")
			}
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"all", "active", "archived"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/listAllotmentBlockNotes"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "list-allotment-block-notes", path, map[string]string{
				"propertyID":         fmt.Sprintf("%v", flagPropertyID),
				"allotmentBlockCode": fmt.Sprintf("%v", flagAllotmentBlockCode),
				"status":             fmt.Sprintf("%v", flagStatus),
				"pageNumber":         fmt.Sprintf("%v", flagPageNumber),
				"pageSize":           fmt.Sprintf("%v", flagPageSize),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&flagAllotmentBlockCode, "allotment-block-code", "", "Allotment block code")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Note status (one of: all, active, archived)")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 0, "Page")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "Number of Items per Page (min 1, max 100)")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
