// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetGuestsByStatusPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagStatus string
	var flagPropertyID string
	var flagResultsFrom string
	var flagResultsTo string
	var flagPageNumber int
	var flagPageSize int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-guests-by-status",
		Short:       "Returns a list of guests in the current status (Not Checked In, In House, Checked Out or Cancelled), sorted by...",
		Long:        "Shortcut for 'get-guests-by-status list'. Returns a list of guests in the current status (Not Checked In, In House, Checked Out or Cancelled), sorted by...",
		Example:     "  cloudbeds-pp-cli get-guests-by-status --status example-value",
		Annotations: map[string]string{"pp:endpoint": "get-guests-by-status.list", "pp:method": "GET", "pp:path": "/getGuestsByStatus", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("status") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "status")
			}
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"canceled", "checked_out", "in_house", "not_checked_in"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getGuestsByStatus"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-guests-by-status", path, map[string]string{
				"status":      fmt.Sprintf("%v", flagStatus),
				"propertyID":  fmt.Sprintf("%v", flagPropertyID),
				"resultsFrom": fmt.Sprintf("%v", flagResultsFrom),
				"resultsTo":   fmt.Sprintf("%v", flagResultsTo),
				"pageNumber":  fmt.Sprintf("%v", flagPageNumber),
				"pageSize":    fmt.Sprintf("%v", flagPageSize),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStatus, "status", "", "Guest status during the period (one of: canceled, checked_out, in_house, not_checked_in)")
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "ID for the properties to be queried (comma-separated, i.e. 37,345,89).<br /> It can be omitted if the API key is...")
	cmd.Flags().StringVar(&flagResultsFrom, "results-from", "", "Used to filter guests result, and returns only the guests that were last modified starting on 'resultsFrom' value")
	cmd.Flags().StringVar(&flagResultsTo, "results-to", "", "Used to filter guests result, and returns only the guests that were last modified ending on 'resultsTo' value")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 20, "Results page size. Max = 100")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
