// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetRatePromotedCmd(flags *rootFlags) *cobra.Command {
	var flagRoomTypeID string
	var flagStartDate string
	var flagEndDate string
	var flagAdults int
	var flagChildren int
	var flagDetailedRates bool
	var flagPromoCode bool

	cmd := &cobra.Command{
		Use:         "get-rate",
		Short:       "Returns the rate of the room type selected, based on the provided parameters",
		Long:        "Shortcut for 'get-rate list'. Returns the rate of the room type selected, based on the provided parameters",
		Example:     "  cloudbeds-pp-cli get-rate --room-type-id 550e8400-e29b-41d4-a716-446655440000 --start-date 2026-01-15 --end-date 2026-01-15",
		Annotations: map[string]string{"pp:endpoint": "get-rate.list", "pp:method": "GET", "pp:path": "/getRate", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("room-type-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "room-type-id")
			}
			if !cmd.Flags().Changed("start-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "start-date")
			}
			if !cmd.Flags().Changed("end-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "end-date")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getRate"
			params := map[string]string{}
			if flagRoomTypeID != "" {
				params["roomTypeID"] = fmt.Sprintf("%v", flagRoomTypeID)
			}
			if flagStartDate != "" {
				params["startDate"] = fmt.Sprintf("%v", flagStartDate)
			}
			if flagEndDate != "" {
				params["endDate"] = fmt.Sprintf("%v", flagEndDate)
			}
			if flagAdults != 0 {
				params["adults"] = fmt.Sprintf("%v", flagAdults)
			}
			if flagChildren != 0 {
				params["children"] = fmt.Sprintf("%v", flagChildren)
			}
			if flagDetailedRates != false {
				params["detailedRates"] = fmt.Sprintf("%v", flagDetailedRates)
			}
			if flagPromoCode != false {
				params["promoCode"] = fmt.Sprintf("%v", flagPromoCode)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "get-rate", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagRoomTypeID, "room-type-id", "", "Room Type ID")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Check-in date")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Check-out date")
	cmd.Flags().IntVar(&flagAdults, "adults", 0, "Number of adults")
	cmd.Flags().IntVar(&flagChildren, "children", 0, "Number of children")
	cmd.Flags().BoolVar(&flagDetailedRates, "detailed-rates", false, "If the rates need detailed information")
	cmd.Flags().BoolVar(&flagPromoCode, "promo-code", false, "Return information for one or more specific rate plans by promo code. This parameter is DEPRECATED and not...")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
