// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetHousekeepingStatusPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagRoomTypeIDs string
	var flagHousekeeperIDs string
	var flagRoomCondition string
	var flagRoomOccupied bool
	var flagPageNumber int
	var flagPageSize int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-housekeeping-status",
		Short:       "Returns the current date's housekeeping information The housekeeping status is calculated basing on the set of...",
		Long:        "Shortcut for 'get-housekeeping-status list'. Returns the current date's housekeeping information The housekeeping status is calculated basing on the set of...",
		Example:     "  cloudbeds-pp-cli get-housekeeping-status",
		Annotations: map[string]string{"pp:endpoint": "get-housekeeping-status.list", "pp:method": "GET", "pp:path": "/getHousekeepingStatus", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("room-condition") {
				allowedRoomCondition := []string{"clean", "dirty"}
				validRoomCondition := false
				for _, v := range allowedRoomCondition {
					if flagRoomCondition == v {
						validRoomCondition = true
						break
					}
				}
				if !validRoomCondition {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "room-condition", flagRoomCondition, allowedRoomCondition)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getHousekeepingStatus"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-housekeeping-status", path, map[string]string{
				"propertyID":     fmt.Sprintf("%v", flagPropertyID),
				"roomTypeIDs":    fmt.Sprintf("%v", flagRoomTypeIDs),
				"housekeeperIDs": fmt.Sprintf("%v", flagHousekeeperIDs),
				"roomCondition":  fmt.Sprintf("%v", flagRoomCondition),
				"roomOccupied":   fmt.Sprintf("%v", flagRoomOccupied),
				"pageNumber":     fmt.Sprintf("%v", flagPageNumber),
				"pageSize":       fmt.Sprintf("%v", flagPageSize),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&flagRoomTypeIDs, "room-type-i-ds", "", "Filter by room type ID. If more than one, send as comma-separated, i.e. 37,345,89")
	cmd.Flags().StringVar(&flagHousekeeperIDs, "housekeeper-i-ds", "", "Use this parameter to filter by housekeeper. If you need to specify multiple housekeepers, send their IDs as a...")
	cmd.Flags().StringVar(&flagRoomCondition, "room-condition", "", "Condition of room (one of: clean, dirty)")
	cmd.Flags().BoolVar(&flagRoomOccupied, "room-occupied", false, "Flag for current room occupation status")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "Results page size. Max = 5000")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
