// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetGuestListPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyIDs string
	var flagResultsFrom string
	var flagResultsTo string
	var flagCheckInFrom string
	var flagCheckInTo string
	var flagCheckOutFrom string
	var flagCheckOutTo string
	var flagGuestFirstName string
	var flagGuestLastName string
	var flagGuestEmail string
	var flagGuestPhone string
	var flagGuestCellPhone string
	var flagStatus string
	var flagSortBy string
	var flagIncludeGuestInfo bool
	var flagExcludeSecondaryGuests bool
	var flagIncludeGuestRequirements bool
	var flagPageNumber int
	var flagPageSize int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-guest-list",
		Short:       "Returns a list of guests, ordered by modification date ### Group account support",
		Long:        "Shortcut for 'get-guest-list list'. Returns a list of guests, ordered by modification date ### Group account support",
		Example:     "  cloudbeds-pp-cli get-guest-list",
		Annotations: map[string]string{"pp:endpoint": "get-guest-list.list", "pp:method": "GET", "pp:path": "/getGuestList", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"in_progress", "confirmed", "not_confirmed", "canceled", "checked_in", "checked_out", "no_show"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			if cmd.Flags().Changed("sort-by") {
				allowedSortBy := []string{"creation", "modification"}
				validSortBy := false
				for _, v := range allowedSortBy {
					if flagSortBy == v {
						validSortBy = true
						break
					}
				}
				if !validSortBy {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort-by", flagSortBy, allowedSortBy)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getGuestList"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-guest-list", path, map[string]string{
				"propertyIDs":              fmt.Sprintf("%v", flagPropertyIDs),
				"resultsFrom":              fmt.Sprintf("%v", flagResultsFrom),
				"resultsTo":                fmt.Sprintf("%v", flagResultsTo),
				"checkInFrom":              fmt.Sprintf("%v", flagCheckInFrom),
				"checkInTo":                fmt.Sprintf("%v", flagCheckInTo),
				"checkOutFrom":             fmt.Sprintf("%v", flagCheckOutFrom),
				"checkOutTo":               fmt.Sprintf("%v", flagCheckOutTo),
				"guestFirstName":           fmt.Sprintf("%v", flagGuestFirstName),
				"guestLastName":            fmt.Sprintf("%v", flagGuestLastName),
				"guestEmail":               fmt.Sprintf("%v", flagGuestEmail),
				"guestPhone":               fmt.Sprintf("%v", flagGuestPhone),
				"guestCellPhone":           fmt.Sprintf("%v", flagGuestCellPhone),
				"status":                   fmt.Sprintf("%v", flagStatus),
				"sortBy":                   fmt.Sprintf("%v", flagSortBy),
				"includeGuestInfo":         fmt.Sprintf("%v", flagIncludeGuestInfo),
				"excludeSecondaryGuests":   fmt.Sprintf("%v", flagExcludeSecondaryGuests),
				"includeGuestRequirements": fmt.Sprintf("%v", flagIncludeGuestRequirements),
				"pageNumber":               fmt.Sprintf("%v", flagPageNumber),
				"pageSize":                 fmt.Sprintf("%v", flagPageSize),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyIDs, "property-i-ds", "", "List of property IDs, comma-separated, i.e. 37,345,89")
	cmd.Flags().StringVar(&flagResultsFrom, "results-from", "", "Inferior limit datetime, used to filter guests result, based on latest creation/modification date")
	cmd.Flags().StringVar(&flagResultsTo, "results-to", "", "Superior limit datetime, used to filter guests result, based on latest creation/modification date")
	cmd.Flags().StringVar(&flagCheckInFrom, "check-in-from", "", "Filters guests result to return only guests with check-in date range starting on this date")
	cmd.Flags().StringVar(&flagCheckInTo, "check-in-to", "", "Filters guests result to return only guests with check-in date range ending on this date")
	cmd.Flags().StringVar(&flagCheckOutFrom, "check-out-from", "", "Filters guests result to return only guests with check-out date range starting on this date")
	cmd.Flags().StringVar(&flagCheckOutTo, "check-out-to", "", "Filters guests result to return only guests with check-out date range ending on this date")
	cmd.Flags().StringVar(&flagGuestFirstName, "guest-first-name", "", "Filters guests result based on Guest First Name")
	cmd.Flags().StringVar(&flagGuestLastName, "guest-last-name", "", "Filters guests result based on Guest Last Name")
	cmd.Flags().StringVar(&flagGuestEmail, "guest-email", "", "Filters guests result based on Guest Email")
	cmd.Flags().StringVar(&flagGuestPhone, "guest-phone", "", "Filters guests result based on Guest Phone Number")
	cmd.Flags().StringVar(&flagGuestCellPhone, "guest-cell-phone", "", "Filters guests result based on Guest Cell Phone Number")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Reservation status <br /> If more than one, send as comma-separated values. i.e. in_progress,confirmed (one of: in_progress, confirmed, not_confirmed, canceled, checked_in, checked_out, no_show)")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "modification", "Sort By parameter (one of: creation, modification)")
	cmd.Flags().BoolVar(&flagIncludeGuestInfo, "include-guest-info", false, "If API response should return with more of Guest's information")
	cmd.Flags().BoolVar(&flagExcludeSecondaryGuests, "exclude-secondary-guests", false, "If true, response only returns main guest's")
	cmd.Flags().BoolVar(&flagIncludeGuestRequirements, "include-guest-requirements", false, "Includes guest requirements data in the response")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "Results page size. Max = 100")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
