// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostGuestsToRoomPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyGuestIDs string
	var bodyMainGuestId string
	var bodyPropertyID string
	var bodyRemoveAll bool
	var bodyRemoveGuestIDs string
	var bodyRemoveGuestIDsFromRoom string
	var bodyReservationID string
	var bodyRoomID int

	cmd := &cobra.Command{
		Use:         "post-guests-to-room",
		Short:       "Assigns guest(s) to a room in a reservation and adds these guests as additional guests.",
		Long:        "Shortcut for 'post-guests-to-room create'. Assigns guest(s) to a room in a reservation and adds these guests as additional guests.",
		Example:     "  cloudbeds-pp-cli post-guests-to-room",
		Annotations: map[string]string{"pp:endpoint": "post-guests-to-room.create", "pp:method": "POST", "pp:path": "/postGuestsToRoom"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postGuestsToRoom"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyGuestIDs != "" {
				body["guestIDs"] = bodyGuestIDs
			}
			if bodyMainGuestId != "" {
				body["mainGuestId"] = bodyMainGuestId
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyRemoveAll != false {
				body["removeAll"] = bodyRemoveAll
			}
			if bodyRemoveGuestIDs != "" {
				body["removeGuestIDs"] = bodyRemoveGuestIDs
			}
			if bodyRemoveGuestIDsFromRoom != "" {
				body["removeGuestIDsFromRoom"] = bodyRemoveGuestIDsFromRoom
			}
			if bodyReservationID != "" {
				body["reservationID"] = bodyReservationID
			}
			if bodyRoomID != 0 {
				body["roomID"] = bodyRoomID
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyGuestIDs, "guest-i-ds", "", "Guest ID(s) to be assigned to room. If more than one, send as comma-separated, i.e. 37,345,89")
	cmd.Flags().StringVar(&bodyMainGuestId, "main-guest-id", "", "Guest ID to promote as main guest of the booking room. MUST be present in guestIDs. When omitted, the room's main...")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().BoolVar(&bodyRemoveAll, "remove-all", false, "If set true, will remove all guests assigned to roomID before assigning guests sent in guestIDs parameter. Main...")
	cmd.Flags().StringVar(&bodyRemoveGuestIDs, "remove-guest-i-ds", "", "If sent, will remove guest ID(s) before adding guests sent in guestIDs parameter. If more than one, send as...")
	cmd.Flags().StringVar(&bodyRemoveGuestIDsFromRoom, "remove-guest-i-ds-from-room", "", "If sent, will remove guest ID(s) only from the specified Room ID(s). If more than one, send as comma-separated, i.e....")
	cmd.Flags().StringVar(&bodyReservationID, "reservation-id", "", "Reservation ID")
	cmd.Flags().IntVar(&bodyRoomID, "room-id", 0, "Room ID already assigned to Reservation")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
