// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newCreateAllotmentBlockPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAllotmentBlockName string
	var bodyAllotmentBlockStatus string
	var bodyAllotmentIntervals string
	var bodyAllotmentType string
	var bodyAllowOverbooking bool
	var bodyAutoRelease string
	var bodyEventCode string
	var bodyGroupCode string
	var bodyRatePlanId string
	var bodyRateType string

	cmd := &cobra.Command{
		Use:         "create-allotment-block",
		Short:       "Retreive allotment blocks @apiQuery {Integer} propertyID Property ID",
		Long:        "Shortcut for 'create-allotment-block create'. Retreive allotment blocks @apiQuery {Integer} propertyID Property ID",
		Example:     "  cloudbeds-pp-cli create-allotment-block",
		Annotations: map[string]string{"pp:endpoint": "create-allotment-block.create", "pp:method": "POST", "pp:path": "/createAllotmentBlock"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/createAllotmentBlock"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAllotmentBlockName != "" {
				body["allotmentBlockName"] = bodyAllotmentBlockName
			}
			if bodyAllotmentBlockStatus != "" {
				body["allotmentBlockStatus"] = bodyAllotmentBlockStatus
			}
			if bodyAllotmentIntervals != "" {
				var parsedAllotmentIntervals any
				if err := json.Unmarshal([]byte(bodyAllotmentIntervals), &parsedAllotmentIntervals); err != nil {
					return fmt.Errorf("parsing --allotment-intervals JSON: %w", err)
				}
				body["allotmentIntervals"] = parsedAllotmentIntervals
			}
			if bodyAllotmentType != "" {
				body["allotmentType"] = bodyAllotmentType
			}
			if bodyAllowOverbooking != false {
				body["allowOverbooking"] = bodyAllowOverbooking
			}
			if bodyAutoRelease != "" {
				var parsedAutoRelease any
				if err := json.Unmarshal([]byte(bodyAutoRelease), &parsedAutoRelease); err != nil {
					return fmt.Errorf("parsing --auto-release JSON: %w", err)
				}
				body["autoRelease"] = parsedAutoRelease
			}
			if bodyEventCode != "" {
				body["eventCode"] = bodyEventCode
			}
			if bodyGroupCode != "" {
				body["groupCode"] = bodyGroupCode
			}
			if bodyRatePlanId != "" {
				body["ratePlanId"] = bodyRatePlanId
			}
			if bodyRateType != "" {
				body["rateType"] = bodyRateType
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAllotmentBlockName, "allotment-block-name", "", "The name for the allotment block")
	cmd.Flags().StringVar(&bodyAllotmentBlockStatus, "allotment-block-status", "", "The status for the allotment block under")
	cmd.Flags().StringVar(&bodyAllotmentIntervals, "allotment-intervals", "", "The day-based data for the allotment block.")
	cmd.Flags().StringVar(&bodyAllotmentType, "allotment-type", "", "The allotment type")
	cmd.Flags().BoolVar(&bodyAllowOverbooking, "allow-overbooking", false, "If false, or omitted, then this command will fail if it would result in an overbooking. If true, then the update...")
	cmd.Flags().StringVar(&bodyAutoRelease, "auto-release", "", "Optional auto-release configuration")
	cmd.Flags().StringVar(&bodyEventCode, "event-code", "", "The unique identifier of the event the allotment block should be created")
	cmd.Flags().StringVar(&bodyGroupCode, "group-code", "", "The unique identifier of the group profile the allotment block should be created")
	cmd.Flags().StringVar(&bodyRatePlanId, "rate-plan-id", "", "The rate plan ID. Required if rateType is 'rate_plan'.")
	cmd.Flags().StringVar(&bodyRateType, "rate-type", "", "The rate type for the associated intervals")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
