// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetRoomsFeesAndTaxesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagStartDate string
	var flagEndDate string
	var flagRoomsTotal float64
	var flagRoomsCount int
	var flagAdultsPerRoom int
	var flagChildrenPerRoom int

	cmd := &cobra.Command{
		Use:         "get-rooms-fees-and-taxes",
		Short:       "Get applicable fees and tax to a booking. This is meant to be used on checkout to display to the guest.",
		Long:        "Shortcut for 'get-rooms-fees-and-taxes list'. Get applicable fees and tax to a booking. This is meant to be used on checkout to display to the guest.",
		Example:     "  cloudbeds-pp-cli get-rooms-fees-and-taxes --start-date 2026-01-15 --end-date 2026-01-15 --rooms-total 42 --rooms-count 50",
		Annotations: map[string]string{"pp:endpoint": "get-rooms-fees-and-taxes.list", "pp:method": "GET", "pp:path": "/getRoomsFeesAndTaxes", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("start-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "start-date")
			}
			if !cmd.Flags().Changed("end-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "end-date")
			}
			if !cmd.Flags().Changed("rooms-total") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "rooms-total")
			}
			if !cmd.Flags().Changed("rooms-count") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "rooms-count")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getRoomsFeesAndTaxes"
			params := map[string]string{}
			if flagPropertyID != "" {
				params["propertyID"] = fmt.Sprintf("%v", flagPropertyID)
			}
			if flagStartDate != "" {
				params["startDate"] = fmt.Sprintf("%v", flagStartDate)
			}
			if flagEndDate != "" {
				params["endDate"] = fmt.Sprintf("%v", flagEndDate)
			}
			if flagRoomsTotal != 0.0 {
				params["roomsTotal"] = fmt.Sprintf("%v", flagRoomsTotal)
			}
			if flagRoomsCount != 0 {
				params["roomsCount"] = fmt.Sprintf("%v", flagRoomsCount)
			}
			if flagAdultsPerRoom != 0 {
				params["adultsPerRoom"] = fmt.Sprintf("%v", flagAdultsPerRoom)
			}
			if flagChildrenPerRoom != 0 {
				params["childrenPerRoom"] = fmt.Sprintf("%v", flagChildrenPerRoom)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "get-rooms-fees-and-taxes", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Check-in date")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Check-out date")
	cmd.Flags().Float64Var(&flagRoomsTotal, "rooms-total", 0.0, "Total value of the rooms to be booked, with included taxes")
	cmd.Flags().IntVar(&flagRoomsCount, "rooms-count", 0, "Number of rooms to be booked")
	cmd.Flags().IntVar(&flagAdultsPerRoom, "adults-per-room", 0, "Adult occupants per room (applied uniformly across `roomsCount`). Required for `fixed_per_person` taxes/fees to...")
	cmd.Flags().IntVar(&flagChildrenPerRoom, "children-per-room", 0, "Child occupants per room. Same semantics as `adultsPerRoom`.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
