// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetReservationsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagStatus string
	var flagResultsFrom string
	var flagResultsTo string
	var flagModifiedFrom string
	var flagModifiedTo string
	var flagCheckInFrom string
	var flagCheckInTo string
	var flagCheckOutFrom string
	var flagCheckOutTo string
	var flagDatesQueryMode string
	var flagRoomID string
	var flagRoomName string
	var flagRoomTypeID string
	var flagIncludeGuestsDetails bool
	var flagIncludeGuestRequirements bool
	var flagIncludeCustomFields bool
	var flagIncludeAllRooms bool
	var flagSourceId string
	var flagSourceReservationId string
	var flagRatePlanId string
	var flagFirstName string
	var flagLastName string
	var flagGuestID string
	var flagAllotmentBlockCode string
	var flagGroupCode string
	var flagSortByRecent bool
	var flagPageNumber int
	var flagPageSize int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-reservations",
		Short:       "Returns a list of reservations that matched the filters criteria.<br /> Please note that some reservations...",
		Long:        "Shortcut for 'get-reservations list'. Returns a list of reservations that matched the filters criteria.<br /> Please note that some reservations...",
		Example:     "  cloudbeds-pp-cli get-reservations",
		Annotations: map[string]string{"pp:endpoint": "get-reservations.list", "pp:method": "GET", "pp:path": "/getReservations", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"not_confirmed", "confirmed", "canceled", "checked_in", "checked_out", "no_show"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			if cmd.Flags().Changed("dates-query-mode") {
				allowedDatesQueryMode := []string{"booking", "rooms"}
				validDatesQueryMode := false
				for _, v := range allowedDatesQueryMode {
					if flagDatesQueryMode == v {
						validDatesQueryMode = true
						break
					}
				}
				if !validDatesQueryMode {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "dates-query-mode", flagDatesQueryMode, allowedDatesQueryMode)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getReservations"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-reservations", path, map[string]string{
				"propertyID":               fmt.Sprintf("%v", flagPropertyID),
				"status":                   fmt.Sprintf("%v", flagStatus),
				"resultsFrom":              fmt.Sprintf("%v", flagResultsFrom),
				"resultsTo":                fmt.Sprintf("%v", flagResultsTo),
				"modifiedFrom":             fmt.Sprintf("%v", flagModifiedFrom),
				"modifiedTo":               fmt.Sprintf("%v", flagModifiedTo),
				"checkInFrom":              fmt.Sprintf("%v", flagCheckInFrom),
				"checkInTo":                fmt.Sprintf("%v", flagCheckInTo),
				"checkOutFrom":             fmt.Sprintf("%v", flagCheckOutFrom),
				"checkOutTo":               fmt.Sprintf("%v", flagCheckOutTo),
				"datesQueryMode":           fmt.Sprintf("%v", flagDatesQueryMode),
				"roomID":                   fmt.Sprintf("%v", flagRoomID),
				"roomName":                 fmt.Sprintf("%v", flagRoomName),
				"roomTypeID":               fmt.Sprintf("%v", flagRoomTypeID),
				"includeGuestsDetails":     fmt.Sprintf("%v", flagIncludeGuestsDetails),
				"includeGuestRequirements": fmt.Sprintf("%v", flagIncludeGuestRequirements),
				"includeCustomFields":      fmt.Sprintf("%v", flagIncludeCustomFields),
				"includeAllRooms":          fmt.Sprintf("%v", flagIncludeAllRooms),
				"sourceId":                 fmt.Sprintf("%v", flagSourceId),
				"sourceReservationId":      fmt.Sprintf("%v", flagSourceReservationId),
				"ratePlanId":               fmt.Sprintf("%v", flagRatePlanId),
				"firstName":                fmt.Sprintf("%v", flagFirstName),
				"lastName":                 fmt.Sprintf("%v", flagLastName),
				"guestID":                  fmt.Sprintf("%v", flagGuestID),
				"allotmentBlockCode":       fmt.Sprintf("%v", flagAllotmentBlockCode),
				"groupCode":                fmt.Sprintf("%v", flagGroupCode),
				"sortByRecent":             fmt.Sprintf("%v", flagSortByRecent),
				"pageNumber":               fmt.Sprintf("%v", flagPageNumber),
				"pageSize":                 fmt.Sprintf("%v", flagPageSize),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "ID for the properties to be queried (comma-separated, i.e. 37,345,89).<br /> It can be omitted if the API key is...")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Filter by current reservation status (one of: not_confirmed, confirmed, canceled, checked_in, checked_out, no_show)")
	cmd.Flags().StringVar(&flagResultsFrom, "results-from", "", "Inferior limit datetime, used to filter reservations, based on booking date")
	cmd.Flags().StringVar(&flagResultsTo, "results-to", "", "Superior limit datetime, used to filter reservations, based on booking date")
	cmd.Flags().StringVar(&flagModifiedFrom, "modified-from", "", "Inferior limit datetime, used to filter reservations, based on booking modification date")
	cmd.Flags().StringVar(&flagModifiedTo, "modified-to", "", "Superior limit datetime, used to filter reservations, based on booking modification date")
	cmd.Flags().StringVar(&flagCheckInFrom, "check-in-from", "", "Filters reservations result to return only reservations with check-in date range starting on this date")
	cmd.Flags().StringVar(&flagCheckInTo, "check-in-to", "", "Filters reservations result to return only reservations with check-in date range ending on this date")
	cmd.Flags().StringVar(&flagCheckOutFrom, "check-out-from", "", "Filters reservations result to return only reservations with check-out date range starting on this date")
	cmd.Flags().StringVar(&flagCheckOutTo, "check-out-to", "", "Filters reservations result to return only reservations with check-out date range ending on this date")
	cmd.Flags().StringVar(&flagDatesQueryMode, "dates-query-mode", "booking", "If we should consider the booking's check-in/check-out dates or the start and end dates for the associated rooms. (one of: booking, rooms)")
	cmd.Flags().StringVar(&flagRoomID, "room-id", "", "Filters reservation with the supplied room ID. CheckIn/checkOut dates OR status are required. If dates are provided...")
	cmd.Flags().StringVar(&flagRoomName, "room-name", "", "Filters reservation with the supplied room name (customizable by each property). CheckIn/checkOut dates OR status...")
	cmd.Flags().StringVar(&flagRoomTypeID, "room-type-id", "", "Filters reservation with the supplied Room Type ID.")
	cmd.Flags().BoolVar(&flagIncludeGuestsDetails, "include-guests-details", false, "If guests details should be included or not")
	cmd.Flags().BoolVar(&flagIncludeGuestRequirements, "include-guest-requirements", false, "Includes guest requirements data in the response. Requires `includeGuestsDetails=true`.")
	cmd.Flags().BoolVar(&flagIncludeCustomFields, "include-custom-fields", false, "If reservation custom fields should be included or not")
	cmd.Flags().BoolVar(&flagIncludeAllRooms, "include-all-rooms", false, "When specified, the response will include an additional rooms field that combines both unassigned and assigned rooms.")
	cmd.Flags().StringVar(&flagSourceId, "source-id", "", "Filters reservation with the supplied source ID.")
	cmd.Flags().StringVar(&flagSourceReservationId, "source-reservation-id", "", "Filters reservation with the supplied reservation source ID.")
	cmd.Flags().StringVar(&flagRatePlanId, "rate-plan-id", "", "Filters reservation with the supplied rate plan ID.")
	cmd.Flags().StringVar(&flagFirstName, "first-name", "", "Filters reservation with the supplied primary guest first name.")
	cmd.Flags().StringVar(&flagLastName, "last-name", "", "Filters reservation with the supplied primary guest last name.")
	cmd.Flags().StringVar(&flagGuestID, "guest-id", "", "Filters reservation with the supplied Guest ID (Including additional guests).")
	cmd.Flags().StringVar(&flagAllotmentBlockCode, "allotment-block-code", "", "Filters reservation with the supplied allotment block code.")
	cmd.Flags().StringVar(&flagGroupCode, "group-code", "", "Filters reservation with the supplied group code.")
	cmd.Flags().BoolVar(&flagSortByRecent, "sort-by-recent", false, "Sort response results by most recent action")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "Results page size. Max = 100")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
