// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostItemCategoryPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyCategoryCode string
	var bodyCategoryColor string
	var bodyCategoryName string
	var bodyItemID string
	var bodyPropertyID string

	cmd := &cobra.Command{
		Use:         "post-item-category",
		Short:       "Adds new items category",
		Long:        "Shortcut for 'post-item-category create'. Adds new items category",
		Example:     "  cloudbeds-pp-cli post-item-category",
		Annotations: map[string]string{"pp:endpoint": "post-item-category.create", "pp:method": "POST", "pp:path": "/postItemCategory"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postItemCategory"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyCategoryCode != "" {
				body["categoryCode"] = bodyCategoryCode
			}
			if bodyCategoryColor != "" {
				body["categoryColor"] = bodyCategoryColor
			}
			if bodyCategoryName != "" {
				body["categoryName"] = bodyCategoryName
			}
			if bodyItemID != "" {
				var parsedItemID any
				if err := json.Unmarshal([]byte(bodyItemID), &parsedItemID); err != nil {
					return fmt.Errorf("parsing --item-id JSON: %w", err)
				}
				body["itemID"] = parsedItemID
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCategoryCode, "category-code", "", "Category code")
	cmd.Flags().StringVar(&bodyCategoryColor, "category-color", "#ccc", "Category color (like #3b7be7)")
	cmd.Flags().StringVar(&bodyCategoryName, "category-name", "", "Category name")
	cmd.Flags().StringVar(&bodyItemID, "item-id", "", "Existing ItemIDs to reassign to new category")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
