// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostGuestPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyCustomFields string
	var bodyGuestAddress1 string
	var bodyGuestAddress2 string
	var bodyGuestBirthDate string
	var bodyGuestCellPhone string
	var bodyGuestCity string
	var bodyGuestCompanyName string
	var bodyGuestCompanyTaxId string
	var bodyGuestCountry string
	var bodyGuestDocumentExpirationDate string
	var bodyGuestDocumentIssueDate string
	var bodyGuestDocumentIssuingCountry string
	var bodyGuestDocumentNumber string
	var bodyGuestDocumentType string
	var bodyGuestEmail string
	var bodyGuestFirstName string
	var bodyGuestGender string
	var bodyGuestLastName string
	var bodyGuestNote string
	var bodyGuestPhone string
	var bodyGuestRequirements string
	var bodyGuestState string
	var bodyGuestTaxId string
	var bodyGuestZip string
	var bodyPropertyID string
	var bodyReservationID string
	var bodyReservationNote string

	cmd := &cobra.Command{
		Use:         "post-guest",
		Short:       "Adds a guest to reservation as an additional guest.",
		Long:        "Shortcut for 'post-guest create'. Adds a guest to reservation as an additional guest.",
		Example:     "  cloudbeds-pp-cli post-guest",
		Annotations: map[string]string{"pp:endpoint": "post-guest.create", "pp:method": "POST", "pp:path": "/postGuest"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postGuest"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyCustomFields != "" {
				var parsedCustomFields any
				if err := json.Unmarshal([]byte(bodyCustomFields), &parsedCustomFields); err != nil {
					return fmt.Errorf("parsing --custom-fields JSON: %w", err)
				}
				body["customFields"] = parsedCustomFields
			}
			if bodyGuestAddress1 != "" {
				body["guestAddress1"] = bodyGuestAddress1
			}
			if bodyGuestAddress2 != "" {
				body["guestAddress2"] = bodyGuestAddress2
			}
			if bodyGuestBirthDate != "" {
				body["guestBirthDate"] = bodyGuestBirthDate
			}
			if bodyGuestCellPhone != "" {
				body["guestCellPhone"] = bodyGuestCellPhone
			}
			if bodyGuestCity != "" {
				body["guestCity"] = bodyGuestCity
			}
			if bodyGuestCompanyName != "" {
				body["guestCompanyName"] = bodyGuestCompanyName
			}
			if bodyGuestCompanyTaxId != "" {
				body["guestCompanyTaxId"] = bodyGuestCompanyTaxId
			}
			if bodyGuestCountry != "" {
				body["guestCountry"] = bodyGuestCountry
			}
			if bodyGuestDocumentExpirationDate != "" {
				body["guestDocumentExpirationDate"] = bodyGuestDocumentExpirationDate
			}
			if bodyGuestDocumentIssueDate != "" {
				body["guestDocumentIssueDate"] = bodyGuestDocumentIssueDate
			}
			if bodyGuestDocumentIssuingCountry != "" {
				body["guestDocumentIssuingCountry"] = bodyGuestDocumentIssuingCountry
			}
			if bodyGuestDocumentNumber != "" {
				body["guestDocumentNumber"] = bodyGuestDocumentNumber
			}
			if bodyGuestDocumentType != "" {
				body["guestDocumentType"] = bodyGuestDocumentType
			}
			if bodyGuestEmail != "" {
				body["guestEmail"] = bodyGuestEmail
			}
			if bodyGuestFirstName != "" {
				body["guestFirstName"] = bodyGuestFirstName
			}
			if bodyGuestGender != "" {
				body["guestGender"] = bodyGuestGender
			}
			if bodyGuestLastName != "" {
				body["guestLastName"] = bodyGuestLastName
			}
			if bodyGuestNote != "" {
				body["guestNote"] = bodyGuestNote
			}
			if bodyGuestPhone != "" {
				body["guestPhone"] = bodyGuestPhone
			}
			if bodyGuestRequirements != "" {
				var parsedGuestRequirements any
				if err := json.Unmarshal([]byte(bodyGuestRequirements), &parsedGuestRequirements); err != nil {
					return fmt.Errorf("parsing --guest-requirements JSON: %w", err)
				}
				body["guestRequirements"] = parsedGuestRequirements
			}
			if bodyGuestState != "" {
				body["guestState"] = bodyGuestState
			}
			if bodyGuestTaxId != "" {
				body["guestTaxId"] = bodyGuestTaxId
			}
			if bodyGuestZip != "" {
				body["guestZip"] = bodyGuestZip
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyReservationID != "" {
				body["reservationID"] = bodyReservationID
			}
			if bodyReservationNote != "" {
				body["reservationNote"] = bodyReservationNote
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyCustomFields, "custom-fields", "", "Only guest custom fields are allowed.")
	cmd.Flags().StringVar(&bodyGuestAddress1, "guest-address1", "", "Guest address1")
	cmd.Flags().StringVar(&bodyGuestAddress2, "guest-address2", "", "Guest address2")
	cmd.Flags().StringVar(&bodyGuestBirthDate, "guest-birth-date", "", "Guest birth date")
	cmd.Flags().StringVar(&bodyGuestCellPhone, "guest-cell-phone", "", "Guest cell phone")
	cmd.Flags().StringVar(&bodyGuestCity, "guest-city", "", "Guest city")
	cmd.Flags().StringVar(&bodyGuestCompanyName, "guest-company-name", "", "Guest company name")
	cmd.Flags().StringVar(&bodyGuestCompanyTaxId, "guest-company-tax-id", "", "Guest company tax ID")
	cmd.Flags().StringVar(&bodyGuestCountry, "guest-country", "", "ISO-Code for Country (2 characters)")
	cmd.Flags().StringVar(&bodyGuestDocumentExpirationDate, "guest-document-expiration-date", "", "(mandatory when guestDocumentType is sent and is not DNI, NIE, or CPF)")
	cmd.Flags().StringVar(&bodyGuestDocumentIssueDate, "guest-document-issue-date", "", "(mandatory when guestDocumentType is sent and is not DNI or CPF)")
	cmd.Flags().StringVar(&bodyGuestDocumentIssuingCountry, "guest-document-issuing-country", "", "Valid ISO-Code for Country (2 characters) (mandatory when guestDocumentType is sent)")
	cmd.Flags().StringVar(&bodyGuestDocumentNumber, "guest-document-number", "", "(mandatory when guestDocumentType is sent)")
	cmd.Flags().StringVar(&bodyGuestDocumentType, "guest-document-type", "", "Document Type<br /> dni - Identity card<br /> nie - Residence permit<br /> na - non selection<br /> cpf - Brazilian...")
	cmd.Flags().StringVar(&bodyGuestEmail, "guest-email", "", "Guest email")
	cmd.Flags().StringVar(&bodyGuestFirstName, "guest-first-name", "", "Guest first name")
	cmd.Flags().StringVar(&bodyGuestGender, "guest-gender", "", "Guest gender")
	cmd.Flags().StringVar(&bodyGuestLastName, "guest-last-name", "", "Guest last name")
	cmd.Flags().StringVar(&bodyGuestNote, "guest-note", "", "Note to be added to the Guest")
	cmd.Flags().StringVar(&bodyGuestPhone, "guest-phone", "", "Guest phone")
	cmd.Flags().StringVar(&bodyGuestRequirements, "guest-requirements", "", "Object with guest requirements information.")
	cmd.Flags().StringVar(&bodyGuestState, "guest-state", "", "Guest state")
	cmd.Flags().StringVar(&bodyGuestTaxId, "guest-tax-id", "", "Guest tax ID")
	cmd.Flags().StringVar(&bodyGuestZip, "guest-zip", "", "Guest zip")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodyReservationID, "reservation-id", "", "Reservation ID")
	cmd.Flags().StringVar(&bodyReservationNote, "reservation-note", "", "Note to be added only to the Reservation.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
