// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostCustomFieldPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyApplyTo string
	var bodyDisplayed string
	var bodyIsPersonal bool
	var bodyMaxCharacters int
	var bodyName string
	var bodyPropertyID string
	var bodyRequired bool
	var bodyShortcode string
	var bodyType string

	cmd := &cobra.Command{
		Use:         "post-custom-field",
		Short:       "Sets custom fields. The call should only be made once to add the field to the system.",
		Long:        "Shortcut for 'post-custom-field create'. Sets custom fields. The call should only be made once to add the field to the system.",
		Example:     "  cloudbeds-pp-cli post-custom-field",
		Annotations: map[string]string{"pp:endpoint": "post-custom-field.create", "pp:method": "POST", "pp:path": "/postCustomField"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postCustomField"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyApplyTo != "" {
				body["applyTo"] = bodyApplyTo
			}
			if bodyDisplayed != "" {
				var parsedDisplayed any
				if err := json.Unmarshal([]byte(bodyDisplayed), &parsedDisplayed); err != nil {
					return fmt.Errorf("parsing --displayed JSON: %w", err)
				}
				body["displayed"] = parsedDisplayed
			}
			if bodyIsPersonal != false {
				body["isPersonal"] = bodyIsPersonal
			}
			if bodyMaxCharacters != 0 {
				body["maxCharacters"] = bodyMaxCharacters
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyRequired != false {
				body["required"] = bodyRequired
			}
			if bodyShortcode != "" {
				body["shortcode"] = bodyShortcode
			}
			if bodyType != "" {
				body["type"] = bodyType
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyApplyTo, "apply-to", "reservation", "Where put this field in reservation or guest section of the booking. reservation - applies the custom field to...")
	cmd.Flags().StringVar(&bodyDisplayed, "displayed", "", "¹ Specify where this custom field to show up. reservation - applies the custom field to reservation interface in...")
	cmd.Flags().BoolVar(&bodyIsPersonal, "is-personal", false, "Specifies if the contents of this field may contain personal information. User's personal information may be removed...")
	cmd.Flags().IntVar(&bodyMaxCharacters, "max-characters", 40, "Maximum number of characters allowed to be entered in this field.")
	cmd.Flags().StringVar(&bodyName, "name", "", "Field name")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().BoolVar(&bodyRequired, "required", false, "Specify whether this field is required to be filled out.")
	cmd.Flags().StringVar(&bodyShortcode, "shortcode", "", "Internal reference and is used for integration purposes such as custom links and the API")
	cmd.Flags().StringVar(&bodyType, "type", "input", "The field's input type.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
