// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetAvailableRoomTypesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyIDs string
	var flagStartDate string
	var flagEndDate string
	var flagRooms int
	var flagAdults int
	var flagChildren int
	var flagPromoCode string
	var flagDetailedRates bool
	var flagIncludeSharedRooms bool
	var flagSort string
	var flagOrder string
	var flagMinRate float64
	var flagMaxRate float64
	var flagPageNumber int
	var flagPageSize int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-available-room-types",
		Short:       "Returns a list of room types with availability considering the informed parameters ### Group account support",
		Long:        "Shortcut for 'get-available-room-types list'. Returns a list of room types with availability considering the informed parameters ### Group account support",
		Example:     "  cloudbeds-pp-cli get-available-room-types --start-date 2026-01-15 --end-date 2026-01-15 --rooms 42 --adults 42 --children 42",
		Annotations: map[string]string{"pp:endpoint": "get-available-room-types.list", "pp:method": "GET", "pp:path": "/getAvailableRoomTypes", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("start-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "start-date")
			}
			if !cmd.Flags().Changed("end-date") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "end-date")
			}
			if !cmd.Flags().Changed("children") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "children")
			}
			if cmd.Flags().Changed("sort") {
				allowedSort := []string{"room_name", "hotel_name", "room_price", "hotel_stars"}
				validSort := false
				for _, v := range allowedSort {
					if flagSort == v {
						validSort = true
						break
					}
				}
				if !validSort {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "sort", flagSort, allowedSort)
				}
			}
			if cmd.Flags().Changed("order") {
				allowedOrder := []string{"asc", "desc"}
				validOrder := false
				for _, v := range allowedOrder {
					if flagOrder == v {
						validOrder = true
						break
					}
				}
				if !validOrder {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "order", flagOrder, allowedOrder)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getAvailableRoomTypes"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-available-room-types", path, map[string]string{
				"propertyIDs":        fmt.Sprintf("%v", flagPropertyIDs),
				"startDate":          fmt.Sprintf("%v", flagStartDate),
				"endDate":            fmt.Sprintf("%v", flagEndDate),
				"rooms":              fmt.Sprintf("%v", flagRooms),
				"adults":             fmt.Sprintf("%v", flagAdults),
				"children":           fmt.Sprintf("%v", flagChildren),
				"promoCode":          fmt.Sprintf("%v", flagPromoCode),
				"detailedRates":      fmt.Sprintf("%v", flagDetailedRates),
				"includeSharedRooms": fmt.Sprintf("%v", flagIncludeSharedRooms),
				"sort":               fmt.Sprintf("%v", flagSort),
				"order":              fmt.Sprintf("%v", flagOrder),
				"minRate":            fmt.Sprintf("%v", flagMinRate),
				"maxRate":            fmt.Sprintf("%v", flagMaxRate),
				"pageNumber":         fmt.Sprintf("%v", flagPageNumber),
				"pageSize":           fmt.Sprintf("%v", flagPageSize),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyIDs, "property-i-ds", "", "Property ID list, comma-separated, i.e. 37,345,89")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Check-In date.")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Check-Out date.")
	cmd.Flags().IntVar(&flagRooms, "rooms", 1, "Number of rooms.")
	cmd.Flags().IntVar(&flagAdults, "adults", 1, "Number of adults.")
	cmd.Flags().IntVar(&flagChildren, "children", 0, "Number of children.")
	cmd.Flags().StringVar(&flagPromoCode, "promo-code", "", "Promotional code")
	cmd.Flags().BoolVar(&flagDetailedRates, "detailed-rates", false, "If detailed rates are expected")
	cmd.Flags().BoolVar(&flagIncludeSharedRooms, "include-shared-rooms", false, "Include shared rooms in the result for multiple adults/children")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sort parameter (one of: room_name, hotel_name, room_price, hotel_stars)")
	cmd.Flags().StringVar(&flagOrder, "order", "asc", "Order (one of: asc, desc)")
	cmd.Flags().Float64Var(&flagMinRate, "min-rate", 0.0, "Minimum daily rate. Used to filter results")
	cmd.Flags().Float64Var(&flagMaxRate, "max-rate", 0.0, "Maximum daily rate. Used to filter results")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 20, "Page size")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
