// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetRoomsUnassignedPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyIDs string

	cmd := &cobra.Command{
		Use:         "get-rooms-unassigned",
		Short:       "Returns a list of unassigned rooms in the property. Call is alias of [getRooms](#api-Room-getRooms). Please check...",
		Long:        "Shortcut for 'get-rooms-unassigned list'. Returns a list of unassigned rooms in the property. Call is alias of [getRooms](#api-Room-getRooms). Please check...",
		Example:     "  cloudbeds-pp-cli get-rooms-unassigned",
		Annotations: map[string]string{"pp:endpoint": "get-rooms-unassigned.list", "pp:method": "GET", "pp:path": "/getRoomsUnassigned", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getRoomsUnassigned"
			params := map[string]string{}
			if flagPropertyIDs != "" {
				params["propertyIDs"] = fmt.Sprintf("%v", flagPropertyIDs)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "get-rooms-unassigned", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyIDs, "property-i-ds", "", "List of property IDs, comma-separated, i.e. 37,345,89")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
