// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostEmailSchedulePromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyEmailTemplateID string
	var bodyPropertyID string
	var bodySchedule string
	var bodyScheduleName string

	cmd := &cobra.Command{
		Use:         "post-email-schedule",
		Short:       "Creates a new email schedule for existing email template. Email template can be scheduled based on two parameters:...",
		Long:        "Shortcut for 'post-email-schedule create'. Creates a new email schedule for existing email template. Email template can be scheduled based on two parameters:...",
		Example:     "  cloudbeds-pp-cli post-email-schedule",
		Annotations: map[string]string{"pp:endpoint": "post-email-schedule.create", "pp:method": "POST", "pp:path": "/postEmailSchedule"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postEmailSchedule"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyEmailTemplateID != "" {
				body["emailTemplateID"] = bodyEmailTemplateID
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodySchedule != "" {
				var parsedSchedule any
				if err := json.Unmarshal([]byte(bodySchedule), &parsedSchedule); err != nil {
					return fmt.Errorf("parsing --schedule JSON: %w", err)
				}
				body["schedule"] = parsedSchedule
			}
			if bodyScheduleName != "" {
				body["scheduleName"] = bodyScheduleName
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyEmailTemplateID, "email-template-id", "", "ID of the email template that will be used when sending an email.")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodySchedule, "schedule", "", "Schedule")
	cmd.Flags().StringVar(&bodyScheduleName, "schedule-name", "", "User friendly schedule name that appears in the list. Should contain app name.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
