// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetGroupsPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagGroupCode string
	var flagType string
	var flagStatus string
	var flagCreatedFrom string
	var flagCreatedTo string
	var flagPageSize int
	var flagPageNumber int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-groups",
		Short:       "Returns the groups for a property",
		Long:        "Shortcut for 'get-groups list'. Returns the groups for a property",
		Example:     "  cloudbeds-pp-cli get-groups --property-id 550e8400-e29b-41d4-a716-446655440000",
		Annotations: map[string]string{"pp:endpoint": "get-groups.list", "pp:method": "GET", "pp:path": "/getGroups", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if !cmd.Flags().Changed("property-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "property-id")
			}
			if cmd.Flags().Changed("type") {
				allowedType := []string{"group", "company", "travel_agent"}
				validType := false
				for _, v := range allowedType {
					if flagType == v {
						validType = true
						break
					}
				}
				if !validType {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "type", flagType, allowedType)
				}
			}
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"open", "closed"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "status", flagStatus, allowedStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getGroups"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-groups", path, map[string]string{
				"propertyID":  fmt.Sprintf("%v", flagPropertyID),
				"groupCode":   fmt.Sprintf("%v", flagGroupCode),
				"type":        fmt.Sprintf("%v", flagType),
				"status":      fmt.Sprintf("%v", flagStatus),
				"createdFrom": fmt.Sprintf("%v", flagCreatedFrom),
				"createdTo":   fmt.Sprintf("%v", flagCreatedTo),
				"pageSize":    fmt.Sprintf("%v", flagPageSize),
				"pageNumber":  fmt.Sprintf("%v", flagPageNumber),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&flagGroupCode, "group-code", "", "Unique ID for a group")
	cmd.Flags().StringVar(&flagType, "type", "", "The type of group (one of: group, company, travel_agent)")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Group status (one of: open, closed)")
	cmd.Flags().StringVar(&flagCreatedFrom, "created-from", "", "Datetime (lower limit) to be queried")
	cmd.Flags().StringVar(&flagCreatedTo, "created-to", "", "Datetime (upper limit) to be queried")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "Number of groups to return per page (min: 1, max: 100)")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 0, "Which page in the results to access")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
