// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetGuestsModifiedPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyIDs string
	var flagInHouse bool
	var flagResultsFrom string
	var flagResultsTo string
	var flagCheckInFrom string
	var flagCheckInTo string
	var flagCheckOutFrom string
	var flagCheckOutTo string
	var flagIncludeGuestRequirements bool
	var flagPageNumber int
	var flagPageSize int
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-guests-modified",
		Short:       "Returns a list of guests based on their modification date. Note that when a guest checks in or checks out of a room,...",
		Long:        "Shortcut for 'get-guests-modified list'. Returns a list of guests based on their modification date. Note that when a guest checks in or checks out of a room,...",
		Example:     "  cloudbeds-pp-cli get-guests-modified",
		Annotations: map[string]string{"pp:endpoint": "get-guests-modified.list", "pp:method": "GET", "pp:path": "/getGuestsModified", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getGuestsModified"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-guests-modified", path, map[string]string{
				"propertyIDs":              fmt.Sprintf("%v", flagPropertyIDs),
				"inHouse":                  fmt.Sprintf("%v", flagInHouse),
				"resultsFrom":              fmt.Sprintf("%v", flagResultsFrom),
				"resultsTo":                fmt.Sprintf("%v", flagResultsTo),
				"checkInFrom":              fmt.Sprintf("%v", flagCheckInFrom),
				"checkInTo":                fmt.Sprintf("%v", flagCheckInTo),
				"checkOutFrom":             fmt.Sprintf("%v", flagCheckOutFrom),
				"checkOutTo":               fmt.Sprintf("%v", flagCheckOutTo),
				"includeGuestRequirements": fmt.Sprintf("%v", flagIncludeGuestRequirements),
				"pageNumber":               fmt.Sprintf("%v", flagPageNumber),
				"pageSize":                 fmt.Sprintf("%v", flagPageSize),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyIDs, "property-i-ds", "", "List of property IDs, comma-separated, i.e. 37,345,89")
	cmd.Flags().BoolVar(&flagInHouse, "in-house", false, "When used, and true, will return guests only currently in-house. If the guest checks-out, it will not appear on the...")
	cmd.Flags().StringVar(&flagResultsFrom, "results-from", "", "Inferior limit datetime, used to filter guests result, based on latest creation/modification date")
	cmd.Flags().StringVar(&flagResultsTo, "results-to", "", "Superior limit datetime, used to filter guests result, based on latest creation/modification date")
	cmd.Flags().StringVar(&flagCheckInFrom, "check-in-from", "", "Filters guests result to return only guests with check-in date range starting on this date")
	cmd.Flags().StringVar(&flagCheckInTo, "check-in-to", "", "Filters guests result to return only guests with check-in date range ending on this date")
	cmd.Flags().StringVar(&flagCheckOutFrom, "check-out-from", "", "Filters guests result to return only guests with check-out date range starting on this date")
	cmd.Flags().StringVar(&flagCheckOutTo, "check-out-to", "", "Filters guests result to return only guests with check-out date range ending on this date")
	cmd.Flags().BoolVar(&flagIncludeGuestRequirements, "include-guest-requirements", false, "Includes guest requirements data in the response")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Results page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 100, "Results page size. Max = 100")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
