// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostEmailTemplatePromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAutofillAllLanguages bool
	var bodyBcc string
	var bodyBody string
	var bodyCc string
	var bodyEmailType string
	var bodyFrom string
	var bodyFromName string
	var bodyName string
	var bodyPropertyID string
	var bodyReplyTo string
	var bodyReplyToName string
	var bodySubject string

	cmd := &cobra.Command{
		Use:         "post-email-template",
		Short:       "Creates a new email template. See the full list of available language parameters <a...",
		Long:        "Shortcut for 'post-email-template create'. Creates a new email template. See the full list of available language parameters <a...",
		Example:     "  cloudbeds-pp-cli post-email-template",
		Annotations: map[string]string{"pp:endpoint": "post-email-template.create", "pp:method": "POST", "pp:path": "/postEmailTemplate"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postEmailTemplate"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAutofillAllLanguages != false {
				body["autofillAllLanguages"] = bodyAutofillAllLanguages
			}
			if bodyBcc != "" {
				body["bcc"] = bodyBcc
			}
			if bodyBody != "" {
				var parsedBody any
				if err := json.Unmarshal([]byte(bodyBody), &parsedBody); err != nil {
					return fmt.Errorf("parsing --body JSON: %w", err)
				}
				body["body"] = parsedBody
			}
			if bodyCc != "" {
				body["cc"] = bodyCc
			}
			if bodyEmailType != "" {
				body["emailType"] = bodyEmailType
			}
			if bodyFrom != "" {
				body["from"] = bodyFrom
			}
			if bodyFromName != "" {
				body["fromName"] = bodyFromName
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyReplyTo != "" {
				body["replyTo"] = bodyReplyTo
			}
			if bodyReplyToName != "" {
				body["replyToName"] = bodyReplyToName
			}
			if bodySubject != "" {
				var parsedSubject any
				if err := json.Unmarshal([]byte(bodySubject), &parsedSubject); err != nil {
					return fmt.Errorf("parsing --subject JSON: %w", err)
				}
				body["subject"] = parsedSubject
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().BoolVar(&bodyAutofillAllLanguages, "autofill-all-languages", false, "If set, all languages will be set with the value for the property language. If not informed and only one language is...")
	cmd.Flags().StringVar(&bodyBcc, "bcc", "", "Email address to which the email message may be sent as a Blind Carbon Copy")
	cmd.Flags().StringVar(&bodyBody, "body", "", "Email message body. The body key should be a language code (IETF). A few examples are listed below.")
	cmd.Flags().StringVar(&bodyCc, "cc", "", "Email address to which the email message may be sent as a Carbon Copy")
	cmd.Flags().StringVar(&bodyEmailType, "email-type", "nonMarketing", "Type of the email template: Marketing or Non-Marketing. Only applicable to GDPR-compliant properties.")
	cmd.Flags().StringVar(&bodyFrom, "from", "", "Email address from which the email message may be sent")
	cmd.Flags().StringVar(&bodyFromName, "from-name", "", "from which the email message may be sent. If empty email will be used")
	cmd.Flags().StringVar(&bodyName, "name", "", "Template name")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodyReplyTo, "reply-to", "", "Email address to which the email message may be replied. If empty, the value on from parameter will be used.")
	cmd.Flags().StringVar(&bodyReplyToName, "reply-to-name", "", "Name to which the email message may be replied. If empty, email will be used.")
	cmd.Flags().StringVar(&bodySubject, "subject", "", "Email message subject. The subject key should be a language code (IETF). A few examples are listed below.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
