// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetRoomTypesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyIDs string
	var flagRoomTypeIDs string
	var flagStartDate string
	var flagEndDate string
	var flagAdults int
	var flagChildren int
	var flagDetailedRates bool
	var flagRoomTypeName string
	var flagPropertyCity string
	var flagPropertyName string
	var flagMaxGuests string
	var flagPageNumber int
	var flagPageSize int
	var flagSort string
	var flagAll bool

	cmd := &cobra.Command{
		Use:         "get-room-types",
		Short:       "Returns a list of room types filtered by the selected parameters ### Group account support",
		Long:        "Shortcut for 'get-room-types list'. Returns a list of room types filtered by the selected parameters ### Group account support",
		Example:     "  cloudbeds-pp-cli get-room-types",
		Annotations: map[string]string{"pp:endpoint": "get-room-types.list", "pp:method": "GET", "pp:path": "/getRoomTypes", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getRoomTypes"
			data, prov, err := resolvePaginatedRead(cmd.Context(), c, flags, "get-room-types", path, map[string]string{
				"propertyIDs":   fmt.Sprintf("%v", flagPropertyIDs),
				"roomTypeIDs":   fmt.Sprintf("%v", flagRoomTypeIDs),
				"startDate":     fmt.Sprintf("%v", flagStartDate),
				"endDate":       fmt.Sprintf("%v", flagEndDate),
				"adults":        fmt.Sprintf("%v", flagAdults),
				"children":      fmt.Sprintf("%v", flagChildren),
				"detailedRates": fmt.Sprintf("%v", flagDetailedRates),
				"roomTypeName":  fmt.Sprintf("%v", flagRoomTypeName),
				"propertyCity":  fmt.Sprintf("%v", flagPropertyCity),
				"propertyName":  fmt.Sprintf("%v", flagPropertyName),
				"maxGuests":     fmt.Sprintf("%v", flagMaxGuests),
				"pageNumber":    fmt.Sprintf("%v", flagPageNumber),
				"pageSize":      fmt.Sprintf("%v", flagPageSize),
				"sort":          fmt.Sprintf("%v", flagSort),
			}, nil, flagAll, "", "", "")
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyIDs, "property-i-ds", "", "Property ID list, comma-separated, i.e. 37,345,89")
	cmd.Flags().StringVar(&flagRoomTypeIDs, "room-type-i-ds", "", "Room Type ID list, If more than one, send as comma-separated, i.e. 37,345,89")
	cmd.Flags().StringVar(&flagStartDate, "start-date", "", "Check-in date. Required for the rates to be returned.")
	cmd.Flags().StringVar(&flagEndDate, "end-date", "", "Check-out date. Required for the rates to be returned.")
	cmd.Flags().IntVar(&flagAdults, "adults", 0, "Number of adults. Required for the rates to be returned.")
	cmd.Flags().IntVar(&flagChildren, "children", 0, "Number of children. Required for the rates to be returned.")
	cmd.Flags().BoolVar(&flagDetailedRates, "detailed-rates", false, "If detailed rates are expected")
	cmd.Flags().StringVar(&flagRoomTypeName, "room-type-name", "", "Room type name, used to filter")
	cmd.Flags().StringVar(&flagPropertyCity, "property-city", "", "Hotel city, used to filter")
	cmd.Flags().StringVar(&flagPropertyName, "property-name", "", "Hotel name, used to filter")
	cmd.Flags().StringVar(&flagMaxGuests, "max-guests", "", "Max number of guests, used to filter")
	cmd.Flags().IntVar(&flagPageNumber, "page-number", 1, "Page number")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 20, "Page size")
	cmd.Flags().StringVar(&flagSort, "sort", "", "Sorting rules, semicolon-separated. Format: `field[:direction]`, where `direction` is `asc` or `desc`, defaults to...")
	cmd.Flags().BoolVar(&flagAll, "all", false, "Fetch all pages")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
