// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPostCustomPaymentMethodPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyMethod string
	var bodyMethodName string
	var bodyPropertyID string

	cmd := &cobra.Command{
		Use:         "post-custom-payment-method",
		Short:       "Add a Custom Payment Method to a property. This call does not allow to add Payment Methods: credit cards, bank...",
		Long:        "Shortcut for 'post-custom-payment-method create'. Add a Custom Payment Method to a property. This call does not allow to add Payment Methods: credit cards, bank...",
		Example:     "  cloudbeds-pp-cli post-custom-payment-method",
		Annotations: map[string]string{"pp:endpoint": "post-custom-payment-method.create", "pp:method": "POST", "pp:path": "/postCustomPaymentMethod"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/postCustomPaymentMethod"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyMethod != "" {
				body["method"] = bodyMethod
			}
			if bodyMethodName != "" {
				body["methodName"] = bodyMethodName
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyMethod, "method", "", "Payment Method, value used in future calls. Must be unique for each property and no whitespaces are allowed (use...")
	cmd.Flags().StringVar(&bodyMethodName, "method-name", "", "Payment Method Name, value used to represent the Payment Method. Can use spaces. If nothing is sent, will use value...")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID, if not sent will retrieve property ID from credentials, only one property ID call.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
