// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPutItemToInventoryPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyItemCode string
	var bodyItemDescription string
	var bodyItemID string
	var bodyItemName string
	var bodyItemPrice float64
	var bodyItemQuantity int
	var bodyItemSKU string
	var bodyItemType string
	var bodyPropertyID string
	var bodyReorderThreshold int
	var bodyStockInventory bool
	var bodyStopSell int
	var bodyStopSellMet bool

	cmd := &cobra.Command{
		Use:         "put-item-to-inventory",
		Short:       "Updates an item with information provided<br /> ¹ only if item.stockInventory = true<br />",
		Long:        "Shortcut for 'put-item-to-inventory update'. Updates an item with information provided<br /> ¹ only if item.stockInventory = true<br />",
		Example:     "  cloudbeds-pp-cli put-item-to-inventory",
		Annotations: map[string]string{"pp:endpoint": "put-item-to-inventory.update", "pp:method": "PUT", "pp:path": "/putItemToInventory"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/putItemToInventory"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyItemCode != "" {
				body["itemCode"] = bodyItemCode
			}
			if bodyItemDescription != "" {
				body["itemDescription"] = bodyItemDescription
			}
			if bodyItemID != "" {
				body["itemID"] = bodyItemID
			}
			if bodyItemName != "" {
				body["itemName"] = bodyItemName
			}
			if bodyItemPrice != 0.0 {
				body["itemPrice"] = bodyItemPrice
			}
			if bodyItemQuantity != 0 {
				body["itemQuantity"] = bodyItemQuantity
			}
			if bodyItemSKU != "" {
				body["itemSKU"] = bodyItemSKU
			}
			if bodyItemType != "" {
				body["itemType"] = bodyItemType
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodyReorderThreshold != 0 {
				body["reorderThreshold"] = bodyReorderThreshold
			}
			if bodyStockInventory != false {
				body["stockInventory"] = bodyStockInventory
			}
			if bodyStopSell != 0 {
				body["stopSell"] = bodyStopSell
			}
			if bodyStopSellMet != false {
				body["stopSellMet"] = bodyStopSellMet
			}
			data, _, err := c.Put(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyItemCode, "item-code", "", "Item code")
	cmd.Flags().StringVar(&bodyItemDescription, "item-description", "", "Item description")
	cmd.Flags().StringVar(&bodyItemID, "item-id", "", "Item identifier")
	cmd.Flags().StringVar(&bodyItemName, "item-name", "", "Item name")
	cmd.Flags().Float64Var(&bodyItemPrice, "item-price", 0.0, "Item price")
	cmd.Flags().IntVar(&bodyItemQuantity, "item-quantity", 0, "¹ Current amount of item available")
	cmd.Flags().StringVar(&bodyItemSKU, "item-sku", "", "Item SKU. Will be generated if not set")
	cmd.Flags().StringVar(&bodyItemType, "item-type", "", "Item type")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().IntVar(&bodyReorderThreshold, "reorder-threshold", 0, "¹ Quantity at which to reorder item")
	cmd.Flags().BoolVar(&bodyStockInventory, "stock-inventory", false, "Track stock inventory for this item")
	cmd.Flags().IntVar(&bodyStopSell, "stop-sell", 0, "¹ Quantity at which to stop selling product.")
	cmd.Flags().BoolVar(&bodyStopSellMet, "stop-sell-met", false, "¹ true - Whether item is at or below value set for stop-sell threshold.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
