// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGetTaxesAndFeesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagPropertyID string
	var flagIncludeDeleted bool
	var flagIncludeExpired bool
	var flagIncludeCustomItemTaxes bool
	var flagAvailableFor string
	var flagSourceId string
	var flagIsRootSource bool
	var flagIsHotelCollectBooking bool
	var flagProductId string
	var flagAddonId string

	cmd := &cobra.Command{
		Use:         "get-taxes-and-fees",
		Short:       "Returns the taxes and fees set for the property. Read the [Rate-Based tax (Dynamic Tax)...",
		Long:        "Shortcut for 'get-taxes-and-fees list'. Returns the taxes and fees set for the property. Read the [Rate-Based tax (Dynamic Tax)...",
		Example:     "  cloudbeds-pp-cli get-taxes-and-fees",
		Annotations: map[string]string{"pp:endpoint": "get-taxes-and-fees.list", "pp:method": "GET", "pp:path": "/getTaxesAndFees", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("available-for") {
				allowedAvailableFor := []string{"product", "rate", "fee", "tax", "custom_item", "payment"}
				validAvailableFor := false
				for _, v := range allowedAvailableFor {
					if flagAvailableFor == v {
						validAvailableFor = true
						break
					}
				}
				if !validAvailableFor {
					fmt.Fprintf(os.Stderr, "warning: --%s %q not in allowed set %v\n", "available-for", flagAvailableFor, allowedAvailableFor)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/getTaxesAndFees"
			params := map[string]string{}
			if flagPropertyID != "" {
				params["propertyID"] = fmt.Sprintf("%v", flagPropertyID)
			}
			if flagIncludeDeleted != false {
				params["includeDeleted"] = fmt.Sprintf("%v", flagIncludeDeleted)
			}
			if flagIncludeExpired != false {
				params["includeExpired"] = fmt.Sprintf("%v", flagIncludeExpired)
			}
			if flagIncludeCustomItemTaxes != false {
				params["includeCustomItemTaxes"] = fmt.Sprintf("%v", flagIncludeCustomItemTaxes)
			}
			if flagAvailableFor != "" {
				params["availableFor"] = fmt.Sprintf("%v", flagAvailableFor)
			}
			if flagSourceId != "" {
				params["sourceId"] = fmt.Sprintf("%v", flagSourceId)
			}
			if flagIsRootSource != false {
				params["isRootSource"] = fmt.Sprintf("%v", flagIsRootSource)
			}
			if flagIsHotelCollectBooking != false {
				params["isHotelCollectBooking"] = fmt.Sprintf("%v", flagIsHotelCollectBooking)
			}
			if flagProductId != "" {
				params["productId"] = fmt.Sprintf("%v", flagProductId)
			}
			if flagAddonId != "" {
				params["addonId"] = fmt.Sprintf("%v", flagAddonId)
			}
			data, prov, err := resolveRead(cmd.Context(), c, flags, "get-taxes-and-fees", false, path, params, nil)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPropertyID, "property-id", "", "Property ID")
	cmd.Flags().BoolVar(&flagIncludeDeleted, "include-deleted", false, "If the response should include deleted taxes and fees")
	cmd.Flags().BoolVar(&flagIncludeExpired, "include-expired", false, "If the response should include expired taxes and fees")
	cmd.Flags().BoolVar(&flagIncludeCustomItemTaxes, "include-custom-item-taxes", false, "If the response should include custom item taxes")
	cmd.Flags().StringVar(&flagAvailableFor, "available-for", "", "Filter by entity type applicability (one of: product, rate, fee, tax, custom_item, payment)")
	cmd.Flags().StringVar(&flagSourceId, "source-id", "", "Filter by booking source ID. Requires isRootSource and isHotelCollectBooking.")
	cmd.Flags().BoolVar(&flagIsRootSource, "is-root-source", false, "Root source flag. Required with sourceId.")
	cmd.Flags().BoolVar(&flagIsHotelCollectBooking, "is-hotel-collect-booking", false, "Hotel collect flag. Required with sourceId.")
	cmd.Flags().StringVar(&flagProductId, "product-id", "", "Filter taxes/fees for a product. Mutually exclusive with addonId.")
	cmd.Flags().StringVar(&flagAddonId, "addon-id", "", "Filter taxes/fees for an addon (resolves to product). Mutually exclusive with productId.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
