// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPatchGroupPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyAddress1 string
	var bodyAddress2 string
	var bodyCity string
	var bodyGroupCode string
	var bodyName string
	var bodyPropertyID string
	var bodySourceID string
	var bodyState string
	var bodyStatus string
	var bodyType string
	var bodyZip string

	cmd := &cobra.Command{
		Use:         "patch-group",
		Short:       "Updates an existing group with information provided. At least one information field is required for this call.",
		Long:        "Shortcut for 'patch-group create'. Updates an existing group with information provided. At least one information field is required for this call.",
		Example:     "  cloudbeds-pp-cli patch-group",
		Annotations: map[string]string{"pp:endpoint": "patch-group.create", "pp:method": "POST", "pp:path": "/patchGroup"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/patchGroup"
			// HasStore + non-GET falls through to a live API call here
			// rather than through resolveRead (GET-only internally); a
			// body-aware cached read helper is filed as #425 for when a
			// second store-backed POST-search consumer ships.
			body := map[string]any{}
			if bodyAddress1 != "" {
				body["address1"] = bodyAddress1
			}
			if bodyAddress2 != "" {
				body["address2"] = bodyAddress2
			}
			if bodyCity != "" {
				body["city"] = bodyCity
			}
			if bodyGroupCode != "" {
				body["groupCode"] = bodyGroupCode
			}
			if bodyName != "" {
				body["name"] = bodyName
			}
			if bodyPropertyID != "" {
				body["propertyID"] = bodyPropertyID
			}
			if bodySourceID != "" {
				body["sourceID"] = bodySourceID
			}
			if bodyState != "" {
				body["state"] = bodyState
			}
			if bodyStatus != "" {
				body["status"] = bodyStatus
			}
			if bodyType != "" {
				body["type"] = bodyType
			}
			if bodyZip != "" {
				body["zip"] = bodyZip
			}
			data, _, err := c.Post(path, body)
			prov := attachFreshness(DataProvenance{Source: "live"}, flags)
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Unwrap API response envelopes (e.g. {"status":"success","data":[...]})
			// so output helpers see the inner data, not the wrapper.
			data = extractResponseData(data)

			// Print provenance to stderr
			{
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// CSV bypasses JSON pipe path so --csv works when piped
			if flags.csv {
				return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested.
			if flags.asJSON || !isTerminal(cmd.OutOrStdout()) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&bodyAddress1, "address1", "", "Address line 1 for a group")
	cmd.Flags().StringVar(&bodyAddress2, "address2", "", "Address line 2 for a group")
	cmd.Flags().StringVar(&bodyCity, "city", "", "City for a group")
	cmd.Flags().StringVar(&bodyGroupCode, "group-code", "", "code for a group")
	cmd.Flags().StringVar(&bodyName, "name", "", "Name for a group")
	cmd.Flags().StringVar(&bodyPropertyID, "property-id", "", "Property ID")
	cmd.Flags().StringVar(&bodySourceID, "source-id", "", "Source ID for a group")
	cmd.Flags().StringVar(&bodyState, "state", "", "State for a group")
	cmd.Flags().StringVar(&bodyStatus, "status", "", "Group status")
	cmd.Flags().StringVar(&bodyType, "type", "", "The type of group")
	cmd.Flags().StringVar(&bodyZip, "zip", "", "Zip for a group")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
