// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"text/tabwriter"
	"time"

	"cloudbeds-pp-cli/internal/client"
	"cloudbeds-pp-cli/internal/config"
	"github.com/spf13/cobra"
)

var version = "1.0.0"

type rootFlags struct {
	asJSON        bool
	compact       bool
	csv           bool
	plain         bool
	quiet         bool
	dryRun        bool
	noCache       bool
	noInput       bool
	idempotent    bool
	ignoreMissing bool
	yes           bool
	agent         bool
	selectFields  string
	configPath    string
	profileName   string
	deliverSpec   string
	timeout       time.Duration
	rateLimit     float64
	dataSource    string
	freshnessMeta any

	// deliverBuf captures command output when --deliver is set to a
	// non-stdout sink. Flushed to the sink after Execute returns.
	deliverBuf  *bytes.Buffer
	deliverSink DeliverSink
}

// RootCmd returns the Cobra command tree without executing it. The MCP server
// uses this to mirror every user-facing command as an agent tool.
func RootCmd() *cobra.Command {
	var flags rootFlags
	return newRootCmd(&flags)
}

// Execute runs the CLI in non-interactive mode: never prompts, all values via flags or stdin.
func Execute() error {
	var flags rootFlags
	rootCmd := newRootCmd(&flags)

	err := rootCmd.Execute()
	if err != nil && strings.Contains(err.Error(), "unknown flag") {
		msg := err.Error()
		// Extract the flag name from the error message (e.g., "unknown flag: --foob")
		if idx := strings.Index(msg, "unknown flag: "); idx >= 0 {
			flagStr := strings.TrimSpace(msg[idx+len("unknown flag: "):])
			if suggestion := suggestFlag(flagStr, rootCmd); suggestion != "" {
				return fmt.Errorf("%w\nhint: did you mean --%s?", err, suggestion)
			}
		}
	}
	if err == nil && flags.deliverBuf != nil {
		if derr := Deliver(flags.deliverSink, flags.deliverBuf.Bytes(), flags.compact); derr != nil {
			fmt.Fprintf(os.Stderr, "warning: deliver to %s:%s failed: %v\n", flags.deliverSink.Scheme, flags.deliverSink.Target, derr)
			return derr
		}
	}
	return err
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{
		Use:   "cloudbeds-pp-cli",
		Short: `Cloudbeds CLI — The Cloudbeds CLI nobody else built — full PMS API surface plus a local SQLite mirror, FTS5 search, dated snapshots, an…`,
		Long: `Cloudbeds CLI — The Cloudbeds CLI nobody else built — full PMS API surface plus a local SQLite mirror, FTS5 search, dated snapshots, an…

Highlights (not in the official API docs):
  • housekeeping stale   Find rooms that have been dirty longer than a threshold so you can chase them before arrivals.
  • today   One-shot front-desk dashboard: arrivals, departures, in-house, unassigned, dirty rooms, today's ADR and occupancy.
  • rates drift   Show how rates moved over a window, by date, plan, and room type.
  • occupancy trend   Daily occupancy, ADR, and RevPAR series with week-over-week deltas.
  • sources mix   Bookings, nights, and revenue by source (Booking.com, Expedia, Direct, Airbnb) over a window.
  • payments unpaid   Reservations arriving in the next N days with non-zero balance.
  • reservations no-shows   No-show rate by source, room type, and lead-time bucket; flags repeat no-show guests.
  • guests search   Full-text search across guest name, email, phone, and notes; returns past stays with totals.
  • reconcile   Compare local mirror to live API for a sampled window; emit a typed diff.
  • reservations timeline   Single-reservation forensic view: status changes, payments, notes, room assignments — chronological.
  • audit night   End-of-shift bundle: arrivals not checked-in, departures not checked-out, unbalanced folios, payments since last audit.

Agent mode: add --agent to any command for JSON output + non-interactive mode.
Health check: run 'cloudbeds-pp-cli doctor' to verify auth and connectivity.
See README.md or the bundled SKILL.md for recipes.`,
		SilenceUsage: true,
		Version:      version,
	}
	rootCmd.SetVersionTemplate("cloudbeds-pp-cli {{ .Version }}\n")

	rootCmd.PersistentFlags().BoolVar(&flags.asJSON, "json", false, "Output as JSON")
	rootCmd.PersistentFlags().BoolVar(&flags.compact, "compact", false, "Return only key fields (id, name, status, timestamps) for minimal token usage")
	rootCmd.PersistentFlags().BoolVar(&flags.csv, "csv", false, "Output as CSV (table and array responses)")
	rootCmd.PersistentFlags().BoolVar(&flags.plain, "plain", false, "Output as plain tab-separated text")
	rootCmd.PersistentFlags().BoolVar(&flags.quiet, "quiet", false, "Bare output, one value per line")
	rootCmd.PersistentFlags().StringVar(&flags.configPath, "config", "", "Config file path")
	rootCmd.PersistentFlags().DurationVar(&flags.timeout, "timeout", 30*time.Second, "Request timeout")
	rootCmd.PersistentFlags().BoolVar(&flags.dryRun, "dry-run", false, "Show request without sending")
	rootCmd.PersistentFlags().BoolVar(&flags.noCache, "no-cache", false, "Bypass response cache")
	rootCmd.PersistentFlags().BoolVar(&flags.noInput, "no-input", false, "Disable all interactive prompts (for CI/agents)")
	rootCmd.PersistentFlags().BoolVar(&flags.idempotent, "idempotent", false, "Treat already-existing create results as a successful no-op")
	rootCmd.PersistentFlags().BoolVar(&flags.ignoreMissing, "ignore-missing", false, "Treat missing delete targets as a successful no-op")
	rootCmd.PersistentFlags().StringVar(&flags.selectFields, "select", "", "Comma-separated fields to include in output (e.g. --select id,name,status)")
	rootCmd.PersistentFlags().BoolVar(&flags.yes, "yes", false, "Skip confirmation prompts (for agents and scripts)")
	rootCmd.PersistentFlags().BoolVar(&noColor, "no-color", false, "Disable colored output")
	rootCmd.PersistentFlags().BoolVar(&humanFriendly, "human-friendly", false, "Enable colored output and rich formatting")
	rootCmd.PersistentFlags().BoolVar(&flags.agent, "agent", false, "Set all agent-friendly defaults (--json --compact --no-input --no-color --yes)")
	rootCmd.PersistentFlags().StringVar(&flags.dataSource, "data-source", "auto", "Data source for read commands: auto (live with local fallback), live (API only), local (synced data only)")
	rootCmd.PersistentFlags().StringVar(&flags.profileName, "profile", "", "Apply values from a saved profile (see 'cloudbeds-pp-cli profile list')")
	rootCmd.PersistentFlags().StringVar(&flags.deliverSpec, "deliver", "", "Route output to a sink: stdout (default), file:<path>, webhook:<url>")
	rootCmd.PersistentFlags().Float64Var(&flags.rateLimit, "rate-limit", 0, "Max requests per second (0 to disable)")

	rootCmd.PersistentPreRunE = func(cmd *cobra.Command, args []string) error {
		if flags.deliverSpec != "" {
			sink, err := ParseDeliverSink(flags.deliverSpec)
			if err != nil {
				return err
			}
			flags.deliverSink = sink
			if sink.Scheme != "stdout" && sink.Scheme != "" {
				flags.deliverBuf = &bytes.Buffer{}
				cmd.SetOut(io.MultiWriter(os.Stdout, flags.deliverBuf))
			}
		}
		if flags.profileName != "" {
			profile, err := GetProfile(flags.profileName)
			if err != nil {
				return err
			}
			if profile == nil {
				available := ListProfileNames()
				if len(available) == 0 {
					return fmt.Errorf("profile %q not found (no profiles saved yet; run '%s profile save <name> --<flag> <value>')", flags.profileName, cmd.Root().Name())
				}
				return fmt.Errorf("profile %q not found; available: %s", flags.profileName, strings.Join(available, ", "))
			}
			if err := ApplyProfileToFlags(cmd, profile); err != nil {
				return err
			}
		}
		if flags.agent {
			if !cmd.Flags().Changed("json") {
				flags.asJSON = true
			}
			if !cmd.Flags().Changed("compact") {
				flags.compact = true
			}
			if !cmd.Flags().Changed("no-input") {
				flags.noInput = true
			}
			if !cmd.Flags().Changed("yes") {
				flags.yes = true
			}
			if !cmd.Flags().Changed("no-color") {
				noColor = true
			}
		}
		switch flags.dataSource {
		case "auto", "live", "local":
			// valid
		default:
			return fmt.Errorf("invalid --data-source value %q: must be auto, live, or local", flags.dataSource)
		}
		return nil
	}
	rootCmd.AddCommand(newDoctorCmd(flags))
	rootCmd.AddCommand(newAuthCmd(flags))
	rootCmd.AddCommand(newAgentContextCmd(rootCmd))
	rootCmd.AddCommand(newProfileCmd(flags))
	rootCmd.AddCommand(newFeedbackCmd(flags))
	rootCmd.AddCommand(newWhichCmd(flags))
	rootCmd.AddCommand(newExportCmd(flags))
	rootCmd.AddCommand(newImportCmd(flags))
	rootCmd.AddCommand(newSearchCmd(flags))
	rootCmd.AddCommand(newSyncCmd(flags))
	rootCmd.AddCommand(newTailCmd(flags))
	rootCmd.AddCommand(newAnalyticsCmd(flags))
	rootCmd.AddCommand(newWorkflowCmd(flags))
	rootCmd.AddCommand(newAPICmd(flags))
	// --- Transcendence + snapshot commands (hand-built per absorb manifest) ---
	rootCmd.AddCommand(newTodayCmd(flags))
	rootCmd.AddCommand(newHousekeepingCmd(flags))
	rootCmd.AddCommand(newRatesCmd(flags))
	rootCmd.AddCommand(newOccupancyCmd(flags))
	rootCmd.AddCommand(newSourcesCmd(flags))
	rootCmd.AddCommand(newPaymentsCmd(flags))
	rootCmd.AddCommand(newReservationsCmd(flags))
	rootCmd.AddCommand(newGuestsCmd(flags))
	rootCmd.AddCommand(newReconcileCmd(flags))
	rootCmd.AddCommand(newAuditCmd(flags))
	rootCmd.AddCommand(newSnapshotCmd(flags))
	// --- Endpoint-mirror promoted commands ---
	rootCmd.AddCommand(newAccessTokenPromotedCmd(flags))
	rootCmd.AddCommand(newAppendCustomItemPromotedCmd(flags))
	rootCmd.AddCommand(newCreateAllotmentBlockPromotedCmd(flags))
	rootCmd.AddCommand(newCreateAllotmentBlockNotesPromotedCmd(flags))
	rootCmd.AddCommand(newDeleteAdjustmentPromotedCmd(flags))
	rootCmd.AddCommand(newDeleteAllotmentBlockPromotedCmd(flags))
	rootCmd.AddCommand(newDeleteAppPropertySettingsPromotedCmd(flags))
	rootCmd.AddCommand(newDeleteGuestNotePromotedCmd(flags))
	rootCmd.AddCommand(newDeleteReservationNotePromotedCmd(flags))
	rootCmd.AddCommand(newDeleteRoomBlockPromotedCmd(flags))
	rootCmd.AddCommand(newDeleteWebhookPromotedCmd(flags))
	rootCmd.AddCommand(newGetAllotmentBlocksPromotedCmd(flags))
	rootCmd.AddCommand(newGetAppPropertySettingsPromotedCmd(flags))
	rootCmd.AddCommand(newGetAppSettingsPromotedCmd(flags))
	rootCmd.AddCommand(newGetAppStatePromotedCmd(flags))
	rootCmd.AddCommand(newGetAvailableRoomTypesPromotedCmd(flags))
	rootCmd.AddCommand(newGetCurrencySettingsPromotedCmd(flags))
	rootCmd.AddCommand(newGetCustomFieldsPromotedCmd(flags))
	rootCmd.AddCommand(newGetDashboardPromotedCmd(flags))
	rootCmd.AddCommand(newGetEmailSchedulePromotedCmd(flags))
	rootCmd.AddCommand(newGetEmailTemplatesPromotedCmd(flags))
	rootCmd.AddCommand(newGetFilesPromotedCmd(flags))
	rootCmd.AddCommand(newGetGroupNotesPromotedCmd(flags))
	rootCmd.AddCommand(newGetGroupsPromotedCmd(flags))
	rootCmd.AddCommand(newGetGuestPromotedCmd(flags))
	rootCmd.AddCommand(newGetGuestListPromotedCmd(flags))
	rootCmd.AddCommand(newGetGuestNotesPromotedCmd(flags))
	rootCmd.AddCommand(newGetGuestsByFilterPromotedCmd(flags))
	rootCmd.AddCommand(newGetGuestsByStatusPromotedCmd(flags))
	rootCmd.AddCommand(newGetGuestsModifiedPromotedCmd(flags))
	rootCmd.AddCommand(newGetHotelDetailsPromotedCmd(flags))
	rootCmd.AddCommand(newGetHotelsPromotedCmd(flags))
	rootCmd.AddCommand(newGetHouseAccountListPromotedCmd(flags))
	rootCmd.AddCommand(newGetHousekeepersPromotedCmd(flags))
	rootCmd.AddCommand(newGetHousekeepingStatusPromotedCmd(flags))
	rootCmd.AddCommand(newGetItemPromotedCmd(flags))
	rootCmd.AddCommand(newGetItemCategoriesPromotedCmd(flags))
	rootCmd.AddCommand(newGetItemsPromotedCmd(flags))
	rootCmd.AddCommand(newGetPackageNamesPromotedCmd(flags))
	rootCmd.AddCommand(newGetPackagesPromotedCmd(flags))
	rootCmd.AddCommand(newGetPaymentMethodsPromotedCmd(flags))
	rootCmd.AddCommand(newGetPaymentsCapabilitiesPromotedCmd(flags))
	rootCmd.AddCommand(newGetRatePromotedCmd(flags))
	rootCmd.AddCommand(newGetRateJobsPromotedCmd(flags))
	rootCmd.AddCommand(newGetRatePlansPromotedCmd(flags))
	rootCmd.AddCommand(newGetReservationPromotedCmd(flags))
	rootCmd.AddCommand(newGetReservationAssignmentsPromotedCmd(flags))
	rootCmd.AddCommand(newGetReservationNotesPromotedCmd(flags))
	rootCmd.AddCommand(newGetReservationRoomDetailsPromotedCmd(flags))
	rootCmd.AddCommand(newGetReservationsPromotedCmd(flags))
	rootCmd.AddCommand(newGetReservationsWithRateDetailsPromotedCmd(flags))
	rootCmd.AddCommand(newGetRoomBlocksPromotedCmd(flags))
	rootCmd.AddCommand(newGetRoomTypesPromotedCmd(flags))
	rootCmd.AddCommand(newGetRoomsPromotedCmd(flags))
	rootCmd.AddCommand(newGetRoomsFeesAndTaxesPromotedCmd(flags))
	rootCmd.AddCommand(newGetRoomsUnassignedPromotedCmd(flags))
	rootCmd.AddCommand(newGetSourcesPromotedCmd(flags))
	rootCmd.AddCommand(newGetTaxesAndFeesPromotedCmd(flags))
	rootCmd.AddCommand(newGetUsersPromotedCmd(flags))
	rootCmd.AddCommand(newGetWebhooksPromotedCmd(flags))
	rootCmd.AddCommand(newListAllotmentBlockNotesPromotedCmd(flags))
	rootCmd.AddCommand(newOauthPromotedCmd(flags))
	rootCmd.AddCommand(newPatchGroupPromotedCmd(flags))
	rootCmd.AddCommand(newPatchRatePromotedCmd(flags))
	rootCmd.AddCommand(newPostAdjustmentPromotedCmd(flags))
	rootCmd.AddCommand(newPostAppErrorPromotedCmd(flags))
	rootCmd.AddCommand(newPostAppPropertySettingsPromotedCmd(flags))
	rootCmd.AddCommand(newPostAppStatePromotedCmd(flags))
	rootCmd.AddCommand(newPostChargePromotedCmd(flags))
	rootCmd.AddCommand(newPostCreditCardPromotedCmd(flags))
	rootCmd.AddCommand(newPostCustomFieldPromotedCmd(flags))
	rootCmd.AddCommand(newPostCustomItemPromotedCmd(flags))
	rootCmd.AddCommand(newPostCustomPaymentMethodPromotedCmd(flags))
	rootCmd.AddCommand(newPostEmailSchedulePromotedCmd(flags))
	rootCmd.AddCommand(newPostEmailTemplatePromotedCmd(flags))
	rootCmd.AddCommand(newPostFilePromotedCmd(flags))
	rootCmd.AddCommand(newPostGovernmentReceiptPromotedCmd(flags))
	rootCmd.AddCommand(newPostGroupNotePromotedCmd(flags))
	rootCmd.AddCommand(newPostGuestPromotedCmd(flags))
	rootCmd.AddCommand(newPostGuestDocumentPromotedCmd(flags))
	rootCmd.AddCommand(newPostGuestNotePromotedCmd(flags))
	rootCmd.AddCommand(newPostGuestPhotoPromotedCmd(flags))
	rootCmd.AddCommand(newPostGuestsToRoomPromotedCmd(flags))
	rootCmd.AddCommand(newPostHousekeeperPromotedCmd(flags))
	rootCmd.AddCommand(newPostHousekeepingAssignmentPromotedCmd(flags))
	rootCmd.AddCommand(newPostHousekeepingStatusPromotedCmd(flags))
	rootCmd.AddCommand(newPostItemPromotedCmd(flags))
	rootCmd.AddCommand(newPostItemCategoryPromotedCmd(flags))
	rootCmd.AddCommand(newPostItemsToInventoryPromotedCmd(flags))
	rootCmd.AddCommand(newPostNewHouseAccountPromotedCmd(flags))
	rootCmd.AddCommand(newPostPaymentPromotedCmd(flags))
	rootCmd.AddCommand(newPostReservationPromotedCmd(flags))
	rootCmd.AddCommand(newPostReservationDocumentPromotedCmd(flags))
	rootCmd.AddCommand(newPostReservationNotePromotedCmd(flags))
	rootCmd.AddCommand(newPostRoomAssignPromotedCmd(flags))
	rootCmd.AddCommand(newPostRoomBlockPromotedCmd(flags))
	rootCmd.AddCommand(newPostRoomCheckInPromotedCmd(flags))
	rootCmd.AddCommand(newPostRoomCheckOutPromotedCmd(flags))
	rootCmd.AddCommand(newPostVoidItemPromotedCmd(flags))
	rootCmd.AddCommand(newPostVoidPaymentPromotedCmd(flags))
	rootCmd.AddCommand(newPostWebhookPromotedCmd(flags))
	rootCmd.AddCommand(newPutAppPropertySettingsPromotedCmd(flags))
	rootCmd.AddCommand(newPutGroupPromotedCmd(flags))
	rootCmd.AddCommand(newPutGuestPromotedCmd(flags))
	rootCmd.AddCommand(newPutGuestNotePromotedCmd(flags))
	rootCmd.AddCommand(newPutHouseAccountStatusPromotedCmd(flags))
	rootCmd.AddCommand(newPutHousekeeperPromotedCmd(flags))
	rootCmd.AddCommand(newPutItemToInventoryPromotedCmd(flags))
	rootCmd.AddCommand(newPutRatePromotedCmd(flags))
	rootCmd.AddCommand(newPutReservationPromotedCmd(flags))
	rootCmd.AddCommand(newPutReservationNotePromotedCmd(flags))
	rootCmd.AddCommand(newPutRoomBlockPromotedCmd(flags))
	rootCmd.AddCommand(newUpdateAllotmentBlockPromotedCmd(flags))
	rootCmd.AddCommand(newUpdateAllotmentBlockNotesPromotedCmd(flags))
	rootCmd.AddCommand(newUserinfoPromotedCmd(flags))
	rootCmd.AddCommand(newVersionCliCmd())

	return rootCmd
}

func ExitCode(err error) int {
	var codeErr *cliError
	if As(err, &codeErr) {
		return codeErr.code
	}
	return 1
}

func (f *rootFlags) newClient() (*client.Client, error) {
	cfg, err := config.Load(f.configPath)
	if err != nil {
		return nil, configErr(err)
	}
	c := client.New(cfg, f.timeout, f.rateLimit)
	c.DryRun = f.dryRun
	c.NoCache = f.noCache
	return c, nil
}

func (f *rootFlags) printJSON(w *cobra.Command, v any) error {
	enc := json.NewEncoder(w.OutOrStdout())
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

func (f *rootFlags) printTable(w *cobra.Command, headers []string, rows [][]string) error {
	if f.asJSON {
		return fmt.Errorf("use printJSON for JSON output")
	}
	tw := tabwriter.NewWriter(w.OutOrStdout(), 2, 4, 2, ' ', 0)
	header := ""
	for i, h := range headers {
		if i > 0 {
			header += "\t"
		}
		header += h
	}
	fmt.Fprintln(tw, header)
	for _, row := range rows {
		line := ""
		for i, cell := range row {
			if i > 0 {
				line += "\t"
			}
			line += cell
		}
		fmt.Fprintln(tw, line)
	}
	return tw.Flush()
}

func newVersionCliCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "version",
		Short: "Print version",
		Run: func(cmd *cobra.Command, args []string) {
			fmt.Printf("cloudbeds-pp-cli %s\n", version)
		},
	}
}
