// Copyright 2026 digigrowthagency. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/spf13/cobra"
)

func newTailCmd(flags *rootFlags) *cobra.Command {
	var resource string
	var interval time.Duration
	var follow bool

	cmd := &cobra.Command{
		Use:         "tail [resource]",
		Short:       "Stream live changes by polling the API at regular intervals",
		Annotations: map[string]string{"mcp:read-only": "true"},
		Long: `Tail streams live data changes by polling the API at configurable intervals.
Events are emitted as NDJSON to stdout for piping to other tools.
Gracefully shuts down on SIGTERM/SIGINT.

Note: For APIs with WebSocket or SSE support, a future version will use
native streaming instead of polling.`,
		Example: `  # Tail all changes every 10 seconds
  cloudbeds-pp-cli tail --interval 10s

  # Tail a specific resource
  cloudbeds-pp-cli tail messages --interval 5s

  # Pipe to jq for filtering
  cloudbeds-pp-cli tail events --interval 30s | jq 'select(.type == "error")'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) > 0 {
				resource = args[0]
			}
			// JSON help envelope: when called with no resource AND --json,
			// surface the list of known resources so agents can discover
			// what to pass without parsing a usage error message.
			// Envelope: {resources: [...], note}.
			if resource == "" && flags.asJSON {
				return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
					"resources": tailKnownResources(),
					"note":      "tail requires a resource name; pass one of the listed names",
				}, flags)
			}
			if resource == "" {
				return fmt.Errorf("resource name required (e.g., 'tail messages')")
			}

			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c.NoCache = true

			path := "/" + resource

			sig := make(chan os.Signal, 1)
			signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)

			ticker := time.NewTicker(interval)
			defer ticker.Stop()

			enc := json.NewEncoder(os.Stdout)

			fmt.Fprintf(os.Stderr, "Tailing %s every %s (Ctrl+C to stop)\n", resource, interval)

			// Initial fetch
			if err := fetchAndEmit(c, path, enc); err != nil {
				fmt.Fprintf(os.Stderr, "warning: initial fetch failed: %v\n", err)
			}

			for {
				select {
				case <-sig:
					fmt.Fprintln(os.Stderr, "\nShutting down gracefully...")
					return nil
				case <-ticker.C:
					if err := fetchAndEmit(c, path, enc); err != nil {
						fmt.Fprintf(os.Stderr, "warning: poll failed: %v\n", err)
					}
				}
			}
		},
	}

	cmd.Flags().StringVar(&resource, "resource", "", "Resource type to tail")
	cmd.Flags().DurationVar(&interval, "interval", 10*time.Second, "Poll interval")
	cmd.Flags().BoolVar(&follow, "follow", true, "Keep running (set --follow=false for single poll)")

	return cmd
}

// tailKnownResources returns the resource names this CLI exposes, so the
// no-arg JSON help envelope can list them without depending on sync's
// defaultSyncResources (which only exists when sync is generated).
func tailKnownResources() []string {
	return []string{
		"access-token",
		"append-custom-item",
		"create-allotment-block",
		"create-allotment-block-notes",
		"delete-adjustment",
		"delete-allotment-block",
		"delete-app-property-settings",
		"delete-guest-note",
		"delete-reservation-note",
		"delete-room-block",
		"delete-webhook",
		"get-allotment-blocks",
		"get-app-property-settings",
		"get-app-settings",
		"get-app-state",
		"get-available-room-types",
		"get-currency-settings",
		"get-custom-fields",
		"get-dashboard",
		"get-email-schedule",
		"get-email-templates",
		"get-files",
		"get-group-notes",
		"get-groups",
		"get-guest",
		"get-guest-list",
		"get-guest-notes",
		"get-guests-by-filter",
		"get-guests-by-status",
		"get-guests-modified",
		"get-hotel-details",
		"get-hotels",
		"get-house-account-list",
		"get-housekeepers",
		"get-housekeeping-status",
		"get-item",
		"get-item-categories",
		"get-items",
		"get-package-names",
		"get-packages",
		"get-payment-methods",
		"get-payments-capabilities",
		"get-rate",
		"get-rate-jobs",
		"get-rate-plans",
		"get-reservation",
		"get-reservation-assignments",
		"get-reservation-notes",
		"get-reservation-room-details",
		"get-reservations",
		"get-reservations-with-rate-details",
		"get-room-blocks",
		"get-room-types",
		"get-rooms",
		"get-rooms-fees-and-taxes",
		"get-rooms-unassigned",
		"get-sources",
		"get-taxes-and-fees",
		"get-users",
		"get-webhooks",
		"list-allotment-block-notes",
		"oauth",
		"patch-group",
		"patch-rate",
		"post-adjustment",
		"post-app-error",
		"post-app-property-settings",
		"post-app-state",
		"post-charge",
		"post-credit-card",
		"post-custom-field",
		"post-custom-item",
		"post-custom-payment-method",
		"post-email-schedule",
		"post-email-template",
		"post-file",
		"post-government-receipt",
		"post-group-note",
		"post-guest",
		"post-guest-document",
		"post-guest-note",
		"post-guest-photo",
		"post-guests-to-room",
		"post-housekeeper",
		"post-housekeeping-assignment",
		"post-housekeeping-status",
		"post-item",
		"post-item-category",
		"post-items-to-inventory",
		"post-new-house-account",
		"post-payment",
		"post-reservation",
		"post-reservation-document",
		"post-reservation-note",
		"post-room-assign",
		"post-room-block",
		"post-room-check-in",
		"post-room-check-out",
		"post-void-item",
		"post-void-payment",
		"post-webhook",
		"put-app-property-settings",
		"put-group",
		"put-guest",
		"put-guest-note",
		"put-house-account-status",
		"put-housekeeper",
		"put-item-to-inventory",
		"put-rate",
		"put-reservation",
		"put-reservation-note",
		"put-room-block",
		"update-allotment-block",
		"update-allotment-block-notes",
		"userinfo",
	}
}

func fetchAndEmit(c interface {
	Get(string, map[string]string) (json.RawMessage, error)
}, path string, enc *json.Encoder) error {
	data, err := c.Get(path, nil)
	if err != nil {
		return err
	}

	var items []json.RawMessage
	if err := json.Unmarshal(data, &items); err != nil {
		event := map[string]any{
			"event":     "data",
			"timestamp": time.Now().UTC().Format(time.RFC3339),
			"data":      json.RawMessage(data),
		}
		return enc.Encode(event)
	}

	for _, item := range items {
		event := map[string]any{
			"event":     "data",
			"timestamp": time.Now().UTC().Format(time.RFC3339),
			"data":      item,
		}
		if err := enc.Encode(event); err != nil {
			return err
		}
	}
	return nil
}
